"""Engineering Core, Part 1 decks (topics 1 to 8)."""

P1 = "01-core-component/01-engineering-core-part1.md"

DECKS = [
    {
        "area": "core",
        "file": "core/01-design-principles-and-manufacturing-approaches.pptx",
        "title": "Design Principles and Manufacturing Approaches",
        "unit": "Core topic 1",
        "spec": "1.1, 1.3",
        "pages": [P1],
        "objectives": [
            "Describe the main types of manufacturing process.",
            "Compare linear, iterative and other approaches to design, including the 6Rs.",
            "Relate scale of manufacture to infrastructure and automation.",
            "Explain the role of CAM, quality assurance and quality control.",
        ],
        "starter": "Pick up any object near you. How do you think it was made? Could it be made a different way?",
        "slides": [
            {"type": "cards", "title": "Types of manufacturing process",
             "cards": [
                 ("Wasting", "Removing material: cutting, drilling, milling, turning."),
                 ("Forming and shaping", "Bending or pressing material, or moulding it into shape."),
                 ("Casting", "Pouring molten material into a mould."),
                 ("Joining", "Welding, brazing, fixings, adhesives."),
                 ("Finishing", "Coatings and surface treatments."),
                 ("Additive", "Building layer by layer, e.g. 3D printing."),
             ]},
            {"type": "compare", "title": "Approaches to design",
             "left": ("Linear and iterative", [
                 "Linear: brief, research, specification, ideas, develop, make, evaluate, in order",
                 "Iterative: design, test, evaluate, improve, repeat",
                 "Testing results feed the next iteration",
             ]),
             "right": ("Other approaches", [
                 "Inclusive and user-centred design",
                 "Design for manufacture and assembly",
                 "Sustainable design and the 6Rs: reduce, refuse, rethink, repair, reuse, recycle",
             ]),
             "notes": "Fitness for purpose covers functional and environmental requirements. User requirements come from design briefs and specifications. Students should be able to interpret anthropometric (ergonomic) data."},
            {"type": "table", "title": "Scale of manufacture",
             "header": ["Scale", "Example", "Typical automation"],
             "widths": [1.6, 3.4, 3.6],
             "rows": [
                 ["One-off", "A bespoke racing car part", "Manual or CAM"],
                 ["Batch", "A run of 500 brackets", "CAM with changeovers"],
                 ["Mass", "Car door handles", "Largely automated production lines"],
                 ["Continuous", "Steel sheet, chemicals", "Fully automated, runs non-stop"],
             ]},
            {"type": "cards", "title": "Infrastructure and control",
             "cards": [
                 ("Infrastructure", "Functional, product and matrix layouts; cellular manufacture; production lines."),
                 ("Automation levels", "Manual, computer-aided manufacture (CAM), fully automated, robotic."),
                 ("Control", "Performance monitoring, quality assurance and quality control."),
             ]},
        ],
        "quiz": [
            ("Which type of process removes material?", "Wasting."),
            ("Name three of the 6Rs.", "Any three of: reduce, refuse, rethink, repair, reuse, recycle."),
            ("Which scale of manufacture suits steel sheet?", "Continuous."),
            ("What does CAM stand for?", "Computer-aided manufacture."),
        ],
        "activity": {
            "title": "Make it at scale",
            "time": "25 minutes",
            "format": "Small groups",
            "steps": [
                "Your product is a bike bottle cage.",
                "Suggest how it would be made as a one-off, a batch of 200, and mass produced.",
                "Choose manufacturing processes and automation levels for each.",
                "Apply two of the 6Rs to improve its sustainability.",
            ],
            "success": [
                "Processes match the scale",
                "Automation choices justified",
                "6Rs applied specifically",
            ],
        },
        "exit": [
            "Why is iterative design often better than linear?",
            "Give one advantage of cellular manufacture.",
            "What is the difference between quality assurance and quality control?",
        ],
    },
    {
        "area": "core",
        "file": "core/02-maintenance-repair-and-installation.pptx",
        "title": "Maintenance, Repair and Installation",
        "unit": "Core topic 1",
        "spec": "1.2",
        "pages": [P1],
        "objectives": [
            "Compare planned, reactive, preventative and condition-based maintenance.",
            "Describe maintenance roles and operations.",
            "Explain installation and commissioning requirements.",
            "Explain how maintenance supports the environment.",
        ],
        "starter": "Should you change a car's oil on a schedule, or wait until the engine sounds wrong? Why?",
        "slides": [
            {"type": "table", "title": "Types of maintenance",
             "header": ["Type", "What it means", "Trade-off"],
             "widths": [2.2, 3.4, 3.4],
             "rows": [
                 ["Planned", "Scheduled in advance", "Predictable, but may replace parts early"],
                 ["Reactive", "Fix it when it breaks", "No upfront cost, but unplanned downtime"],
                 ["Preventative", "Regular servicing to stop failures", "Fewer breakdowns, ongoing cost"],
                 ["Condition-based", "Monitor and act when readings change", "Efficient, needs sensors and data"],
             ]},
            {"type": "cards", "title": "Roles and operations",
             "cards": [
                 ("Machine operator", "Runs the equipment and reports faults."),
                 ("Maintenance engineer", "Services, repairs and monitors equipment."),
                 ("Maintenance manager", "Plans schedules, resources and priorities."),
                 ("Operations", "Monitoring, repair, shutdown and servicing."),
             ]},
            {"type": "bullets", "title": "Installation and the future of maintenance",
             "bullets": [
                 "Installation must meet customer, regulatory and manufacturer requirements.",
                 "Commissioning checks new equipment works safely and as specified before use.",
                 "New technology: sensors and data make condition-based monitoring easier.",
                 "Good maintenance reduces waste, energy use and environmental impact.",
                 "Waste from maintenance must be disposed of safely.",
             ],
             "callout": "Well-maintained machines last longer, waste less and are safer."},
        ],
        "quiz": [
            ("Which maintenance type waits until something breaks?", "Reactive."),
            ("What is condition-based monitoring?", "Watching equipment readings and acting when they change."),
            ("Why commission new equipment?", "To prove it works safely and as specified before use."),
            ("Who plans maintenance schedules?", "The maintenance manager."),
        ],
        "activity": {
            "title": "Maintenance plan",
            "time": "20 minutes",
            "format": "Pairs",
            "steps": [
                "Choose a workshop machine such as a pillar drill or lathe.",
                "Write a preventative maintenance schedule.",
                "Suggest one condition you could monitor.",
                "Explain how your plan reduces environmental impact.",
            ],
            "success": [
                "Tasks and frequencies realistic",
                "Monitoring idea is practical",
                "Environmental benefit explained",
            ],
        },
        "exit": [
            "When is reactive maintenance acceptable?",
            "What happens during a shutdown?",
            "Name one tool used in maintenance.",
        ],
    },
    {
        "area": "core",
        "file": "core/03-engineering-past-present-and-future.pptx",
        "title": "Engineering Past, Present and Future",
        "unit": "Core topic 2",
        "spec": "2.1, 2.2, 2.3",
        "pages": [P1],
        "objectives": [
            "Describe the main engineering sectors and their products.",
            "Explain how historical advances shaped society.",
            "Evaluate how emerging technologies may change manufacturing.",
        ],
        "starter": "Which invention has changed the world the most: the electric motor, the internet, or the internal combustion engine?",
        "slides": [
            {"type": "cards", "title": "Engineering sectors",
             "cards": [
                 ("Transport", "Aerospace, automotive, rail, marine."),
                 ("Energy", "Power generation (renewable, non-renewable, nuclear), petrochemical."),
                 ("Industry", "Manufacturing, materials, chemical, control, electrical and electronic."),
                 ("Infrastructure", "Structural, water and waste, telecommunications, logistics."),
                 ("Specialist", "Defence, medical, agriculture."),
             ]},
            {"type": "table", "title": "Historical advances",
             "header": ["Advance", "Impact"],
             "widths": [3, 5.6],
             "rows": [
                 ["New materials", "Stronger, lighter structures and products"],
                 ["Electrical power and lighting", "Factories and homes powered and lit"],
                 ["Internal combustion engine and electric motors", "Modern transport and machinery"],
                 ["Replaceable parts and mass production", "Cheaper goods and new jobs"],
                 ["Radio, television, computers, internet", "Global communication and automation"],
             ],
             "caption": "These shaped transport, healthcare, housing, employment and sustainability."},
            {"type": "cards", "title": "Emerging trends",
             "cards": [
                 ("Digital", "AI, digitalisation, IoT, cloud computing, cyber-physical systems."),
                 ("Automation", "Robotics, drones, autonomous systems."),
                 ("Reality", "Virtual and augmented reality for design and training."),
                 ("Energy", "Distributed energy and hybrid technologies."),
                 ("Sustainability", "The circular economy."),
             ]},
        ],
        "quiz": [
            ("Name three engineering sectors.", "Any three, e.g. aerospace, automotive, marine."),
            ("How did replaceable parts change manufacturing?", "They enabled mass production and easy repair."),
            ("What is a cyber-physical system?", "Physical machinery tightly controlled by software and networks."),
            ("What is the circular economy?", "Keeping materials in use through reuse, repair and recycling."),
        ],
        "activity": {
            "title": "Timeline and forecast",
            "time": "25 minutes",
            "format": "Small groups",
            "steps": [
                "Pick one sector.",
                "Build a timeline of four key advances in that sector.",
                "Predict how two emerging technologies will change it by 2040.",
                "Present your forecast in two minutes.",
            ],
            "success": [
                "Advances in correct order",
                "Social and economic effects explained",
                "Forecast is reasoned",
            ],
        },
        "exit": [
            "Which sector would you most like to work in?",
            "How did computers change manufacturing?",
            "Which emerging trend will affect engineering jobs most?",
        ],
    },
    {
        "area": "core",
        "file": "core/04-engineering-drawings-and-tolerancing.pptx",
        "title": "Engineering Drawings, Dimensions and Tolerancing",
        "unit": "Core topic 3",
        "spec": "3.1, 3.2",
        "pages": [P1],
        "objectives": [
            "Choose drawing types for a purpose and audience.",
            "Interpret title blocks, line types, abbreviations and symbols.",
            "Interpret dimensions and GD&T symbols.",
            "Calculate tolerances, limits and fits.",
        ],
        "starter": "A shaft is drawn as 20 mm diameter. Could a real shaft ever be exactly 20.000 mm? What does that mean for making it?",
        "slides": [
            {"type": "cards", "title": "Drawing types",
             "cards": [
                 ("Sketches and isometric", "Quick ideas and 3D views for discussion."),
                 ("Orthographic projection", "Accurate 2D views for manufacture."),
                 ("Exploded views", "Show how parts assemble."),
                 ("CAD models", "Accurate 3D models that can be simulated."),
                 ("Diagrams", "Block diagrams, flowcharts, circuit diagrams and schematics."),
             ],
             "notes": "Drawings follow BS EN 8888 (technical product documentation) and BS 3939 (graphical symbols)."},
            {"type": "table", "title": "Common abbreviations",
             "header": ["Abbreviation", "Meaning", "Abbreviation", "Meaning"],
             "widths": [1.6, 2.6, 1.6, 2.6],
             "rows": [
                 ["AF", "Across flats", "CSK", "Countersink"],
                 ["CL", "Centre line", "HEX", "Hexagon"],
                 ["DIA", "Diameter", "PCD", "Pitch circle diameter"],
                 ["DWG", "Drawing", "THD", "Thread"],
                 ["MTL", "Material", "UCUT", "Undercut"],
                 ["CHAM", "Chamfer", "SQ / R", "Square / radius"],
             ]},
            {"type": "bullets", "title": "Tolerances, limits and fits",
             "bullets": [
                 "Tolerance: the total allowed variation in a dimension.",
                 "Limits: the largest and smallest acceptable sizes.",
                 "Example: 20 mm plus or minus 0.1 mm gives limits of 19.9 mm and 20.1 mm, a tolerance of 0.2 mm.",
                 "Fits: clearance (always a gap), interference (always tight), transition (either).",
             ],
             "callout": "Tighter tolerances cost more to make. Only specify what the function really needs."},
            {"type": "cards", "title": "Geometric tolerancing (GD&T)",
             "cards": [
                 ("Datum", "A reference surface or feature to measure from."),
                 ("Parallelism", "A surface stays parallel to a datum."),
                 ("Perpendicularity", "A surface stays at 90 degrees to a datum."),
                 ("Concentricity", "Circular features share a centre."),
                 ("Straightness", "A line or edge stays straight."),
             ]},
        ],
        "quiz": [
            ("What does PCD stand for?", "Pitch circle diameter."),
            ("A hole is 12 mm plus or minus 0.05 mm. What are its limits?", "11.95 mm and 12.05 mm."),
            ("Which fit always has a gap?", "A clearance fit."),
            ("Which drawing type is best for showing assembly?", "An exploded view."),
        ],
        "activity": {
            "title": "Read the drawing",
            "time": "25 minutes",
            "format": "Pairs",
            "steps": [
                "Study the orthographic drawing from your teacher.",
                "List every abbreviation and symbol and what it means.",
                "Calculate the limits for three toleranced dimensions.",
                "Identify the fit between the shaft and the hole.",
            ],
            "success": [
                "All symbols correctly explained",
                "Limits calculated accurately",
                "Fit type justified",
            ],
        },
        "exit": [
            "Who would use an isometric sketch rather than an orthographic drawing?",
            "Why do tighter tolerances cost more?",
            "What is a datum?",
        ],
    },
    {
        "area": "core",
        "file": "core/05-essential-mathematics.pptx",
        "title": "Essential Mathematics for Engineering",
        "unit": "Core topic 4",
        "spec": "4.1, 4.2",
        "pages": [P1],
        "objectives": [
            "Apply arithmetic, algebra and geometry to engineering problems.",
            "Use trigonometry, graphs and basic calculus.",
            "Calculate statistical measures.",
            "Convert between decimal, binary and hexadecimal.",
        ],
        "starter": "A ladder 5 m long leans against a wall with its foot 3 m out. How high up the wall does it reach?",
        "slides": [
            {"type": "table", "title": "The maths toolkit",
             "header": ["Area", "What to be able to do"],
             "widths": [2, 6.6],
             "rows": [
                 ["Arithmetic", "Standard form, fractions, percentages, ratios, BIDMAS"],
                 ["Algebra", "Rearrange equations; simultaneous and quadratic equations; indices; logarithms; sequences; matrices"],
                 ["Geometry", "Areas of 2D shapes, volumes of 3D shapes"],
                 ["Calculus", "Straight-line graphs y = mx + c; standard differentials and integrals; maximum and minimum"],
                 ["Trigonometry", "Pythagoras, sine and cosine rules, radians, vectors"],
                 ["Statistics", "Range, mean, median, mode, standard deviation, probability"],
             ],
             "notes": "Starter answer: Pythagoras, height = square root of (25 minus 9) = 4 m."},
            {"type": "bullets", "title": "Worked examples",
             "bullets": [
                 "Standard form: 0.00045 m = 4.5 x 10 to the power -4 m.",
                 "Straight line: through (0, 2) with gradient 3 gives y = 3x + 2.",
                 "Volume of a cylinder: pi x r squared x h. For r = 0.1 m and h = 2 m, about 0.063 cubic metres.",
                 "Sine rule: a / sin A = b / sin B = c / sin C.",
             ],
             "callout": "Always write the formula, substitute with units, then round sensibly. Most marks are lost in the working, not the maths."},
            {"type": "table", "title": "Number systems",
             "header": ["Decimal", "Binary", "Hexadecimal", "Used for"],
             "widths": [1.6, 2, 1.8, 3.2],
             "rows": [
                 ["10", "1010", "A", "Everyday counting"],
                 ["15", "1111", "F", "Binary: digital logic and PLC signals"],
                 ["255", "11111111", "FF", "Hex: memory addresses and machine codes"],
             ]},
        ],
        "quiz": [
            ("Write 0.0032 in standard form.", "3.2 x 10 to the power -3."),
            ("What is the gradient of y = 4x - 7?", "4."),
            ("Convert binary 1100 to decimal.", "12."),
            ("Find the mean of 12, 15, 18.", "15."),
            ("What is 180 degrees in radians?", "Pi radians."),
        ],
        "activity": {
            "title": "Maths in the workshop",
            "time": "30 minutes",
            "format": "Pairs",
            "steps": [
                "Work through the six engineering problems from your teacher (one per toolkit area).",
                "Show the formula, substitution and units every time.",
                "Check each answer with a partner.",
                "Convert three sensor readings from binary to decimal and hex.",
            ],
            "success": [
                "Working shown clearly",
                "Correct units",
                "Conversions correct",
            ],
        },
        "exit": [
            "Which area of maths do you find hardest?",
            "Why do engineers use standard form?",
            "Where might you meet hexadecimal in engineering?",
        ],
    },
    {
        "area": "core",
        "file": "core/06-units-measurement-and-scientific-method.pptx",
        "title": "Units, Measurement and Scientific Method",
        "unit": "Core topic 5",
        "spec": "5.1, 5.2, 5.3, 5.4",
        "pages": [P1],
        "objectives": [
            "Use SI and imperial units and convert between them.",
            "Distinguish vectors and scalars, and polar and Cartesian coordinates.",
            "Apply the scientific method to testing.",
            "Choose measurement equipment and explain accuracy, precision and calibration.",
        ],
        "starter": "Is 'the car travelled 30 miles' a speed, a velocity or a distance? What would make it a velocity?",
        "slides": [
            {"type": "table", "title": "Units",
             "header": ["Quantity", "SI unit", "Note"],
             "widths": [2.4, 2.4, 3.8],
             "rows": [
                 ["Length, mass, time", "m, kg, s", "Base units"],
                 ["Force", "newton (N)", "Derived: kg m/s squared"],
                 ["Pressure", "pascal (Pa)", "N per square metre"],
                 ["Torque", "newton metre (N m)", "Force x distance"],
                 ["Density", "kg per cubic metre", "Mass / volume"],
                 ["Prefixes", "tera to pico", "k = 1,000; m = 0.001; micro = 0.000001"],
             ],
             "caption": "Imperial units: foot, inch, yard, ounce, gallon. 1 inch = 25.4 mm."},
            {"type": "compare", "title": "Vectors and coordinates",
             "left": ("Scalars and vectors", [
                 "Scalar: size only, e.g. distance, speed",
                 "Vector: size and direction, e.g. displacement, velocity, acceleration",
             ]),
             "right": ("Coordinates", [
                 "Cartesian: (x, y)",
                 "Polar: (r, angle)",
                 "x = r cos angle, y = r sin angle",
                 "r = square root of (x squared + y squared)",
             ])},
            {"type": "process", "title": "The scientific method",
             "steps": [
                 ("Observe", "Notice something."),
                 ("Question", "Ask why."),
                 ("Hypothesise", "Suggest an explanation."),
                 ("Predict", "Predict or simulate a result."),
                 ("Test", "Run a fair test."),
                 ("Conclude", "Accept or reject, then iterate."),
             ],
             "caption": "Judge results on accuracy, reliability, precision and whether they can be replicated."},
            {"type": "table", "title": "Measurement equipment",
             "header": ["Equipment", "Measures", "Typical resolution"],
             "widths": [2.6, 3.2, 2.8],
             "rows": [
                 ["Steel rule", "Lengths", "0.5 mm"],
                 ["Vernier / digital calliper", "Inside, outside and depth", "0.02 / 0.01 mm"],
                 ["Micrometer", "Small diameters and thicknesses", "0.01 mm"],
                 ["Dial test indicator", "Small variations, run-out", "0.01 mm"],
                 ["CMM", "Complex 3D geometry", "Microns"],
             ],
             "notes": "Principles: precision (repeatability), accuracy (closeness to the true value), uncertainty, resolution, calibration and tolerance."},
        ],
        "quiz": [
            ("Is velocity a scalar or a vector?", "A vector."),
            ("Convert 3 inches to millimetres.", "76.2 mm."),
            ("What is the difference between accuracy and precision?", "Accuracy is closeness to the true value; precision is repeatability."),
            ("Why calibrate equipment?", "So its readings match a known standard."),
            ("Which tool would you use to measure a 6 mm shaft diameter most precisely?", "A micrometer."),
        ],
        "activity": {
            "title": "Measure and compare",
            "time": "30 minutes",
            "format": "Pairs, practical",
            "steps": [
                "Measure the same three components with a rule, a calliper and a micrometer.",
                "Record five readings each.",
                "Calculate the mean and range for each tool.",
                "Explain which tool is most precise and why.",
            ],
            "success": [
                "Readings recorded with units",
                "Mean and range correct",
                "Conclusion uses accuracy and precision correctly",
            ],
        },
        "exit": [
            "Give a derived SI unit and what it measures.",
            "Why repeat measurements?",
            "What is resolution?",
        ],
    },
    {
        "area": "core",
        "file": "core/07-forces-motion-and-energy.pptx",
        "title": "Forces, Motion and Energy",
        "unit": "Core topics 5 and 7",
        "spec": "5.6, 7.1, 7.2",
        "pages": [P1],
        "objectives": [
            "Describe types of motion and calculate moments and torque.",
            "Apply Newton's three laws of motion.",
            "Calculate beam reactions for simply supported beams.",
            "Calculate work, power and energy, and compare power sources.",
        ],
        "starter": "Why is it easier to open a door by pushing near the handle than near the hinge?",
        "slides": [
            {"type": "cards", "title": "Motion and moments",
             "cards": [
                 ("Types of motion", "Rotary, linear, reciprocating, oscillating."),
                 ("Moment", "Force x perpendicular distance from the pivot (N m)."),
                 ("Equilibrium", "Clockwise moments = anticlockwise moments, and forces balance."),
                 ("Torque", "The turning effect of a force about an axis."),
             ],
             "notes": "Starter: the handle is further from the hinge, so the same force gives a bigger moment."},
            {"type": "cards", "title": "Newton's laws of motion",
             "cards": [
                 ("First law", "An object stays at rest or at constant velocity unless a resultant force acts."),
                 ("Second law", "Force = mass x acceleration (F = ma)."),
                 ("Third law", "Every action has an equal and opposite reaction."),
             ]},
            {"type": "bullets", "title": "Simply supported beams",
             "bullets": [
                 "A beam rests on two supports with loads applied.",
                 "Take moments about one support to find the other reaction.",
                 "Example: a 4 m beam with a 1,000 N load at its centre: each reaction is 500 N.",
                 "Shear force and bending moment diagrams show internal forces along the beam.",
             ],
             "callout": "Check your answer: the two reactions must add up to the total load."},
            {"type": "table", "title": "Energy and power",
             "header": ["Quantity", "Formula"],
             "widths": [3, 5.6],
             "rows": [
                 ["Work done", "Force x distance moved (J)"],
                 ["Power", "Work done / time (W)"],
                 ["Kinetic energy", "Half x mass x velocity squared"],
                 ["Potential energy", "Mass x g x height (g = 9.81 m/s squared)"],
                 ["Momentum", "Mass x velocity; conserved in collisions"],
             ],
             "caption": "Power sources: mechanical, electrical and renewable, e.g. solar, hydro, wind, geothermal, fossil fuels, nuclear."},
        ],
        "quiz": [
            ("A 20 N force acts 0.5 m from a pivot. What is the moment?", "10 N m."),
            ("What force accelerates a 2 kg mass at 3 m/s squared?", "6 N."),
            ("State Newton's third law.", "Every action has an equal and opposite reaction."),
            ("What is the kinetic energy of 4 kg moving at 3 m/s?", "18 J."),
            ("A motor does 600 J of work in 10 s. What is its power?", "60 W."),
        ],
        "activity": {
            "title": "Beam challenge",
            "time": "30 minutes",
            "format": "Pairs",
            "steps": [
                "A 6 m beam carries 2 kN at 2 m from the left support.",
                "Calculate both support reactions.",
                "Sketch the shear force diagram.",
                "Check your reactions add up to the load.",
            ],
            "success": [
                "Moments taken correctly",
                "Reactions of 1.33 kN (left) and 0.67 kN (right)",
                "Diagram labelled",
            ],
            "notes": "Answer: taking moments about the left support, right reaction = 2 x 2 / 6 = 0.67 kN; left reaction = 1.33 kN.",
        },
        "exit": [
            "Give an everyday example of Newton's first law.",
            "Why does a flywheel store energy?",
            "Compare two power sources for a remote farm.",
        ],
    },
    {
        "area": "core",
        "file": "core/08-fluid-dynamics-and-thermodynamics.pptx",
        "title": "Fluid Dynamics and Thermodynamics",
        "unit": "Core topic 5",
        "spec": "5.7, 5.8",
        "pages": [P1],
        "objectives": [
            "Explain hydrostatic pressure, viscosity and Bernoulli's principle.",
            "Describe laminar and turbulent flow and aerodynamic forces.",
            "Describe heat transfer and sensible and latent heat.",
            "Apply Boyle's law, Charles' law and the general gas equation.",
        ],
        "starter": "Why do your ears hurt at the bottom of a swimming pool but not at the top?",
        "slides": [
            {"type": "cards", "title": "Fluids at rest and in motion",
             "cards": [
                 ("Hydrostatic pressure", "Pressure = density x g x depth. It rises with depth."),
                 ("Viscosity", "A fluid's resistance to flow: honey is more viscous than water."),
                 ("Bernoulli's principle", "Where a fluid speeds up, its pressure drops."),
                 ("Flow types", "Laminar (smooth layers) and turbulent (chaotic), with vortices and separation points."),
             ]},
            {"type": "cards", "title": "Aerodynamics",
             "cards": [
                 ("Lift", "Upward force from pressure difference across a wing."),
                 ("Drag", "Resistance opposing motion through air."),
                 ("Thrust", "Force that drives an object forward."),
             ],
             "notes": "Liquids are nearly incompressible; air is compressible, which is a key difference between liquid flow and aerodynamics."},
            {"type": "compare", "title": "Heat",
             "left": ("Heat transfer", [
                 "Conduction: through solids",
                 "Convection: by moving fluids",
                 "Radiation: by electromagnetic waves",
                 "Open and closed systems",
             ]),
             "right": ("Types of heat", [
                 "Sensible heat changes temperature",
                 "Latent heat changes state at constant temperature",
                 "Expansivity: materials expand when heated",
             ])},
            {"type": "table", "title": "The gas laws",
             "header": ["Law", "Relationship", "Held constant"],
             "widths": [2.4, 3.6, 2.6],
             "rows": [
                 ["Boyle's law", "p1 V1 = p2 V2", "Temperature"],
                 ["Charles' law", "V1 / T1 = V2 / T2", "Pressure"],
                 ["General gas equation", "p1 V1 / T1 = p2 V2 / T2", "Mass of gas"],
                 ["Characteristic gas equation", "pV = mRT", "R for the gas"],
             ],
             "caption": "Temperatures in gas laws must be in kelvin: K = degrees C + 273."},
        ],
        "quiz": [
            ("What happens to pressure as depth increases?", "It increases."),
            ("State Bernoulli's principle.", "Where a fluid's speed increases, its pressure decreases."),
            ("Which heat changes state without changing temperature?", "Latent heat."),
            ("A gas at 100 kPa is squeezed from 2 L to 1 L at constant temperature. New pressure?", "200 kPa."),
            ("Convert 27 degrees C to kelvin.", "300 K."),
        ],
        "activity": {
            "title": "Gas law problems",
            "time": "25 minutes",
            "format": "Pairs",
            "steps": [
                "Solve the four gas law problems from your teacher.",
                "State which law applies and what is held constant.",
                "Convert all temperatures to kelvin.",
                "Explain one real engineering application of each law.",
            ],
            "success": [
                "Correct law chosen",
                "Kelvin used",
                "Answers with units",
            ],
        },
        "exit": [
            "Why must gas law temperatures be in kelvin?",
            "Give one example of convection in engineering.",
            "Why does a car spoiler create downforce?",
        ],
    },
    {
        "area": "core",
        "file": "core/09-materials-chemistry-properties-and-structures.pptx",
        "title": "Materials: Chemistry, Properties and Structures",
        "unit": "Core topics 5 and 6",
        "spec": "5.5, 6.1, 6.2",
        "pages": [P1],
        "objectives": [
            "Describe atomic structure, bonding and chemical behaviour of materials.",
            "Distinguish physical and mechanical properties and calculate density.",
            "Describe the main families of engineering materials.",
            "Describe smart materials and their uses.",
        ],
        "starter": "Why is a kettle's body made of metal or plastic, but its handle always plastic?",
        "slides": [
            {"type": "cards", "title": "Chemistry for engineers",
             "cards": [
                 ("Atoms", "Nucleus of protons and neutrons, surrounded by electrons; valence electrons form bonds."),
                 ("Bonding", "Metallic, covalent, ionic and van der Waals bonds."),
                 ("Electrical chemistry", "Cells, capacity, internal resistance and electrolysis."),
                 ("Reactions", "Metals react with acids and alkalis: used in etching and surface finishing."),
             ]},
            {"type": "compare", "title": "Properties of materials",
             "left": ("Physical", [
                 "Density = mass / volume",
                 "Melting point",
                 "Thermal and electrical conductivity",
                 "Thermal expansivity, corrosion resistance",
                 "Weldability, recyclability",
             ]),
             "right": ("Mechanical", [
                 "Strength: tensile, compressive, shear, torsion",
                 "Hardness and toughness",
                 "Brittleness and ductility",
                 "Elasticity and plasticity",
                 "Malleability",
             ])},
            {"type": "table", "title": "Families of materials",
             "header": ["Family", "Examples"],
             "widths": [2.6, 6],
             "rows": [
                 ["Ferrous metals", "Cast iron, carbon steels, stainless steel"],
                 ["Non-ferrous metals", "Aluminium, copper, brass, zinc"],
                 ["Thermoplastics / thermosets", "ABS, acrylic / epoxy resin, melamine"],
                 ["Elastomers", "Rubber, neoprene"],
                 ["Composites", "GRP, carbon fibre (CRP), MDF"],
                 ["Ceramics", "Silicon carbide, glass"],
             ]},
            {"type": "cards", "title": "Smart materials",
             "cards": [
                 ("Shape memory alloys", "Return to a set shape when heated."),
                 ("Quantum tunnelling composite", "Conducts when squeezed."),
                 ("Thermochromic / photochromic", "Change colour with heat / light."),
                 ("Piezoelectric crystals", "Produce a voltage when stressed."),
             ]},
        ],
        "quiz": [
            ("A block has mass 2.7 kg and volume 0.001 cubic metres. What is its density?", "2,700 kg per cubic metre (aluminium)."),
            ("What is the difference between hardness and toughness?", "Hardness resists scratching and wear; toughness resists fracture from impact."),
            ("Is brass ferrous or non-ferrous?", "Non-ferrous."),
            ("Which smart material produces a voltage under stress?", "A piezoelectric crystal."),
        ],
        "activity": {
            "title": "Material detective",
            "time": "25 minutes",
            "format": "Small groups",
            "steps": [
                "Examine the material samples from your teacher.",
                "Identify each family and one likely material.",
                "Measure mass and volume to calculate density for two samples.",
                "Match each sample to a suitable product and justify it by properties.",
            ],
            "success": [
                "Families correct",
                "Density calculated with units",
                "Justifications use property names",
            ],
        },
        "exit": [
            "Why are thermosets used for plug sockets?",
            "What is ductility?",
            "Name one use of a shape memory alloy.",
        ],
    },
    {
        "area": "core",
        "file": "core/10-processing-treatment-failure-and-testing.pptx",
        "title": "Material Processing, Treatment, Failure and Testing",
        "unit": "Core topic 6",
        "spec": "6.3, 6.4, 6.5, 6.6",
        "pages": [P1],
        "objectives": [
            "Explain how processing changes material properties.",
            "Describe heat treatments and surface treatments.",
            "Explain causes of failure: corrosion, fatigue and creep.",
            "Interpret tensile test results and calculate stress, strain and Young's modulus.",
        ],
        "starter": "Bend a paperclip back and forth until it snaps. What just happened to the metal?",
        "slides": [
            {"type": "table", "title": "Heat and surface treatments",
             "header": ["Treatment", "Effect"],
             "widths": [2.6, 6],
             "rows": [
                 ["Case hardening", "Hard outer surface, tough core"],
                 ["Quench hardening / tempering", "Harden steel, then reduce brittleness"],
                 ["Normalising / annealing", "Refine grain / soften and relieve stress"],
                 ["Precipitation hardening", "Strengthens some alloys, e.g. aluminium"],
                 ["Painting, plastic coating, galvanising", "Barrier or sacrificial protection against corrosion"],
             ],
             "notes": "Processing also changes properties: rolling, forging, welding, casting, sintering, hot and cold working, curing thermosets."},
            {"type": "cards", "title": "Why materials fail",
             "cards": [
                 ("Corrosion", "Oxidation, chemical attack or stress corrosion eats material away."),
                 ("Fatigue", "Repeated loading below the breaking stress causes cracks: the paperclip."),
                 ("Creep", "Slow deformation under constant load, often at high temperature, in three stages."),
                 ("Prevention", "Coatings, galvanising, sacrificial anodes, good design."),
             ]},
            {"type": "table", "title": "Tensile testing",
             "header": ["Quantity", "Formula or meaning"],
             "widths": [2.6, 6],
             "rows": [
                 ["Stress", "Force / cross-sectional area (N per square metre, Pa)"],
                 ["Strain", "Extension / original length (no units)"],
                 ["Young's modulus", "Stress / strain, in the elastic region"],
                 ["Hooke's law", "Extension is proportional to load up to the limit of proportionality"],
                 ["Ultimate tensile strength", "The maximum stress before necking and fracture"],
             ],
             "caption": "Other tests: visual, toughness (impact), hardness, corrosion, wear, fatigue (Wohler), conductivity."},
        ],
        "quiz": [
            ("What is fatigue failure?", "Failure caused by repeated cyclic loading below the ultimate strength."),
            ("A 1,000 N force acts on 0.0001 square metres. What is the stress?", "10,000,000 Pa (10 MPa)."),
            ("A 2 m bar stretches 1 mm. What is the strain?", "0.0005."),
            ("Why temper after quench hardening?", "To reduce brittleness."),
        ],
        "activity": {
            "title": "Read a load-extension graph",
            "time": "25 minutes",
            "format": "Pairs",
            "steps": [
                "Use the tensile test data from your teacher.",
                "Mark the elastic limit, UTS and fracture point on the graph.",
                "Calculate stress, strain and Young's modulus in the elastic region.",
                "Identify the material from its modulus.",
            ],
            "success": [
                "Key points labelled",
                "Calculations with units",
                "Sensible identification",
            ],
        },
        "exit": [
            "Why is galvanising called sacrificial protection?",
            "Where would creep be a concern?",
            "What does Young's modulus tell you?",
        ],
    },
    {
        "area": "core",
        "file": "core/11-electrical-and-electronic-principles.pptx",
        "title": "Electrical and Electronic Principles",
        "unit": "Core topic 8",
        "spec": "8.1",
        "pages": [P1],
        "objectives": [
            "Explain charge, current, voltage, resistance and power.",
            "Apply Ohm's law and Kirchhoff's laws to series and parallel circuits.",
            "Describe AC and DC, protection systems and semiconductors.",
            "Compare analogue and digital signals.",
        ],
        "starter": "Why does a fuse blow instead of the wires in your house catching fire?",
        "slides": [
            {"type": "table", "title": "Key quantities",
             "header": ["Quantity", "Unit", "Formula"],
             "widths": [2.4, 2, 4.2],
             "rows": [
                 ["Current (I)", "amp (A)", "Charge / time"],
                 ["Voltage (V)", "volt (V)", "V = I x R (Ohm's law)"],
                 ["Resistance (R)", "ohm", "R = V / I"],
                 ["Power (P)", "watt (W)", "P = V x I"],
             ]},
            {"type": "compare", "title": "Series and parallel",
             "left": ("Series", [
                 "Same current through every component",
                 "Voltages add up to the supply",
                 "Total R = R1 + R2 + ...",
             ]),
             "right": ("Parallel", [
                 "Same voltage across each branch",
                 "Currents add up to the total",
                 "1 / R total = 1 / R1 + 1 / R2 + ...",
             ]),
             "notes": "Kirchhoff's current law: current into a junction equals current out. Voltage law: voltages around a loop sum to zero."},
            {"type": "cards", "title": "AC, protection and components",
             "cards": [
                 ("AC and DC", "AC reverses direction (mains); DC flows one way (batteries). Phasor diagrams show AC phase."),
                 ("Protection", "Fuses, RCDs and lightning arrestors; differential and transformer protection."),
                 ("Capacitors and inductors", "Store energy in electric and magnetic fields; time constants in DC circuits."),
                 ("Semiconductors", "Diodes let current flow one way; transistors switch and amplify."),
             ]},
            {"type": "compare", "title": "Signals",
             "left": ("Analogue", [
                 "Continuously variable",
                 "e.g. a thermistor's voltage",
                 "Affected by noise",
             ]),
             "right": ("Digital", [
                 "Discrete levels: on or off",
                 "e.g. a limit switch",
                 "Robust, easy to process",
                 "Fan in / fan out limits how many gates connect",
             ])},
        ],
        "quiz": [
            ("A 12 V supply drives 2 A. What is the resistance?", "6 ohms."),
            ("Two 10 ohm resistors in series: total resistance?", "20 ohms."),
            ("Two 10 ohm resistors in parallel: total resistance?", "5 ohms."),
            ("What does an RCD do?", "Cuts the supply when it detects a current imbalance (leakage)."),
            ("What does a diode do?", "Lets current flow in one direction only."),
        ],
        "activity": {
            "title": "Circuit calculations",
            "time": "30 minutes",
            "format": "Pairs, with breadboards if available",
            "steps": [
                "Build (or sketch) a series and a parallel circuit with two resistors.",
                "Predict currents and voltages using Ohm's law.",
                "Measure them with a multimeter.",
                "Explain any differences between prediction and measurement.",
            ],
            "success": [
                "Predictions calculated correctly",
                "Meter used safely",
                "Differences explained (tolerance, meter resistance)",
            ],
        },
        "exit": [
            "Why are house circuits wired in parallel?",
            "What is the power of a 230 V, 5 A heater?",
            "Give one advantage of digital signals.",
        ],
    },
]
