"""Engineering Core, Part 2 decks (topics 9 to 17) and the Employer-set Project deck."""

P2 = "01-core-component/02-engineering-core-part2.md"
ESP = "01-core-component/03-employer-set-project.md"

DECKS = [
    {
        "area": "core",
        "file": "core/12-mechatronics.pptx",
        "title": "Mechatronics, PLCs, Hydraulics and Pneumatics",
        "unit": "Core topic 9",
        "spec": "9.1, 9.2, 9.3",
        "pages": [P2],
        "objectives": [
            "Identify the mechanical, electronic and drive components of a mechatronic system.",
            "Compare PLC types and explain how a PLC operates.",
            "Compare hydraulic and pneumatic systems and their components.",
        ],
        "starter": "A car wash moves along a car, sprays, brushes and dries it. List every sensor and motor you think it needs.",
        "slides": [
            {"type": "cards", "title": "Components of a mechatronic system",
             "cards": [
                 ("Mechanical", "Gears, cams, linkages, levers, pulleys."),
                 ("Electronic", "Sensors, transducers, microprocessors, microcontrollers, actuators."),
                 ("Drives", "Standard electric motors, servo motors, stepper motors."),
             ],
             "notes": "Mechatronics integrates mechanical and electronic systems into one functioning system. Servo motors give precise position control with feedback; stepper motors move in fixed steps."},
            {"type": "cards", "title": "Programmable logic controllers (PLCs)",
             "cards": [
                 ("Types", "Unitary, unitary with modular features, and modular."),
                 ("Operation", "Condition sensor signals, run the program, drive outputs."),
                 ("Function", "Process blocks, motor driver ICs, interface devices."),
                 ("Applications", "Robotic arms, conveyors, packaging, SCADA, remote units, animatronics."),
             ],
             "notes": "Compared with dedicated ICs or computers, PLCs are rugged, easily reprogrammed and built for industrial I/O, but cost more than a simple dedicated circuit."},
            {"type": "compare", "title": "Hydraulics and pneumatics",
             "left": ("Hydraulics (oil)", [
                 "Nearly incompressible fluid",
                 "Very high forces, precise control",
                 "Risk of leaks and fire from oil",
                 "e.g. excavators, presses",
             ]),
             "right": ("Pneumatics (air)", [
                 "Compressible, so springy",
                 "Fast, clean and cheap",
                 "Lower forces, less precise",
                 "e.g. pick-and-place, doors on buses",
             ]),
             "notes": "Components: valves, pumps, actuators, cylinders, compressors. Students should recognise them on schematic diagrams."},
        ],
        "quiz": [
            ("Name two electronic components in a mechatronic system.", "Any two of: sensors, transducers, microprocessors, microcontrollers, actuators."),
            ("What is the difference between a unitary and a modular PLC?", "A unitary PLC is a single fixed unit; a modular PLC is built from plug-in modules."),
            ("Which system uses a nearly incompressible fluid?", "Hydraulics."),
            ("Which motor moves in fixed steps?", "A stepper motor."),
        ],
        "activity": {
            "title": "Design a sorting system",
            "time": "30 minutes",
            "format": "Small groups",
            "steps": [
                "A conveyor must push large boxes onto a second belt and let small boxes pass.",
                "Choose sensors, a PLC type and an actuator.",
                "Decide between pneumatic and hydraulic actuation and justify it.",
                "Sketch a block diagram of the system.",
            ],
            "success": [
                "Input, process and output all present",
                "Actuator choice justified",
                "Diagram is clear",
            ],
        },
        "exit": [
            "Why are PLCs popular in factories?",
            "When would you choose pneumatics?",
            "What does a transducer do?",
        ],
    },
    {
        "area": "core",
        "file": "core/13-control-systems.pptx",
        "title": "Control Systems, Sensors and Actuators",
        "unit": "Core topic 10",
        "spec": "10.1, 10.2",
        "pages": [P2],
        "objectives": [
            "Describe inputs, processes and outputs, including logic gates.",
            "Compare open and closed loop control and explain feedback.",
            "Explain steady-state error, damping and signal types.",
            "Describe sensors and actuators used in automation.",
        ],
        "starter": "A toaster runs for a set time. An oven holds 180 degrees. Which one 'knows' what is happening? How?",
        "slides": [
            {"type": "cards", "title": "Parts of a control system",
             "cards": [
                 ("Input", "Sensors measuring pressure, flow, temperature, speed or position."),
                 ("Process", "Logic gates (AND, OR, NOT), timers, comparators, counters, latches."),
                 ("Output", "Motors, valves, heaters, lamps."),
                 ("Feedback", "The output is measured and fed back to the input."),
             ]},
            {"type": "compare", "title": "Open and closed loop",
             "left": ("Open loop", [
                 "No feedback",
                 "Simple and cheap",
                 "Cannot correct errors",
                 "e.g. a toaster on a timer",
             ]),
             "right": ("Closed loop", [
                 "Feedback via a summing point compares output to the set point",
                 "Corrects errors automatically",
                 "Can overshoot (under-damped) or be slow (over-damped)",
                 "e.g. an oven thermostat, cruise control",
             ]),
             "notes": "Steady-state error is the difference that remains between the set point and the output once the system settles. A transfer function describes the output/input relationship of a block."},
            {"type": "table", "title": "Signals and modulation",
             "header": ["Term", "Meaning"],
             "widths": [2.6, 6],
             "rows": [
                 ["Analogue signal", "Continuously variable value"],
                 ["Digital signal", "Discrete on or off levels"],
                 ["Pulse width modulation", "Varies the on-time of pulses to control power, e.g. motor speed"],
                 ["Pulse amplitude modulation", "Varies the height of pulses to carry information"],
             ]},
            {"type": "cards", "title": "Sensors and actuators in automation",
             "cards": [
                 ("Types", "Analogue or digital; active (needs power) or passive."),
                 ("Examples", "Switches, proximity sensors, lasers, vision systems."),
                 ("Connections", "Hard-wired or wireless; suitable power sources."),
                 ("Uses", "Positioning, measuring, lifting and moving objects."),
             ]},
        ],
        "quiz": [
            ("What does a closed loop system have that an open loop one doesn't?", "Feedback."),
            ("Which logic gate outputs 1 only when both inputs are 1?", "AND."),
            ("What is steady-state error?", "The difference left between the set point and the output once settled."),
            ("How does PWM control motor speed?", "By varying how long the power is on in each pulse."),
        ],
        "activity": {
            "title": "System diagram",
            "time": "25 minutes",
            "format": "Pairs",
            "steps": [
                "Draw a closed loop system diagram for a greenhouse that controls temperature and watering.",
                "Show two inputs, two outputs, the controller and feedback paths.",
                "Label the summing points and set points.",
                "Explain what would happen if it were under-damped.",
            ],
            "success": [
                "Multiple inputs and outputs shown",
                "Feedback correctly drawn",
                "Damping explained",
            ],
        },
        "exit": [
            "Give an example of a passive sensor.",
            "Why might a system overshoot?",
            "Name one process block used in control systems.",
        ],
    },
    {
        "area": "core",
        "file": "core/14-quality-management.pptx",
        "title": "Quality Management and SOPs",
        "unit": "Core topic 11",
        "spec": "11.1, 11.2",
        "pages": [P2],
        "objectives": [
            "Describe quality standards and the role of engineering bodies.",
            "Distinguish quality assurance from quality control.",
            "Explain SPC, six sigma, TQM and quality improvement tools.",
            "Describe the purpose, format and use of SOPs.",
        ],
        "starter": "Would you rather inspect every single bolt a factory makes, or a sample? What are the risks of each?",
        "slides": [
            {"type": "cards", "title": "Standards and bodies",
             "cards": [
                 ("Standards", "British Standards, ISO standards (e.g. ISO 9001), CE marking."),
                 ("Engineering bodies", "Engineering Council, IET, IMechE, SOE, CIBSE, IAgrE, IMI, TWI."),
             ]},
            {"type": "compare", "title": "Quality assurance and quality control",
             "left": ("Quality assurance", [
                 "Prevents defects through good processes",
                 "A culture of quality; right first time",
                 "Document and version control; traceability",
                 "ISO 9001 quality management",
             ]),
             "right": ("Quality control", [
                 "Finds defects by inspection and testing",
                 "Checks products against specification",
                 "Statistical process control (SPC) samples production",
                 "Process capability shows if a process can meet tolerances",
             ])},
            {"type": "cards", "title": "Improving quality",
             "cards": [
                 ("Six sigma", "Data-driven reduction of variation, for high-volume manufacture."),
                 ("TQM", "Total quality management: everyone responsible for quality."),
                 ("FMEA", "List failure modes and their effects before they happen."),
                 ("Pareto analysis", "80% of problems often come from 20% of causes."),
                 ("Cause and effect", "Fishbone diagrams find root causes."),
                 ("Quality circles", "Small teams of workers solving quality problems."),
             ]},
            {"type": "bullets", "title": "Standard operating procedures",
             "bullets": [
                 "Types: manufacturing, quality and maintenance SOPs.",
                 "Purpose: standardise activity, satisfy customers, keep people safe, support training.",
                 "Typical format: title, purpose, scope, responsibilities, equipment, step-by-step method, safety notes, revision history.",
                 "They are produced, implemented and evaluated, then updated under version control.",
             ],
             "callout": "An SOP means the job is done the same safe way whoever does it."},
        ],
        "quiz": [
            ("Is inspection quality assurance or quality control?", "Quality control."),
            ("When is SPC better than 100% inspection?", "In high-volume production where checking every item is too slow or costly."),
            ("What does a Pareto chart show?", "Which few causes create most of the problems."),
            ("Give two purposes of an SOP.", "Any two of: standardising work, customer satisfaction, safety, training."),
        ],
        "activity": {
            "title": "Write an SOP",
            "time": "25 minutes",
            "format": "Pairs",
            "steps": [
                "Choose a workshop task, e.g. setting up a pillar drill.",
                "Write an SOP using the typical format.",
                "Swap with another pair and follow it exactly.",
                "Improve anything that was unclear.",
            ],
            "success": [
                "Safety steps included",
                "Another pair could follow it",
                "Revision history updated",
            ],
        },
        "exit": [
            "Why does document control matter?",
            "What is 'right first time'?",
            "Which engineering body would a mechanical engineer join?",
        ],
    },
    {
        "area": "core",
        "file": "core/15-health-and-safety-legislation.pptx",
        "title": "Health and Safety Legislation and Responsibilities",
        "unit": "Core topic 12",
        "spec": "12.1, 12.2, 12.3",
        "pages": [P2, "02-occupational-specialism/01-knowledge-criteria.md"],
        "objectives": [
            "Describe the main requirements of key health and safety legislation.",
            "Explain why health and safety practice matters, including wellbeing.",
            "Describe employer and employee responsibilities.",
        ],
        "starter": "Who is responsible if a worker is hurt using a machine with its guard removed: the worker, the supervisor or the company?",
        "slides": [
            {"type": "table", "title": "Key legislation",
             "header": ["Legislation", "Covers"],
             "widths": [3.4, 5.2],
             "rows": [
                 ["HASAWA and Management Regulations", "General duties; risk assessment and safety management"],
                 ["PUWER and LOLER", "Safe work equipment; lifting operations and equipment"],
                 ["PPE and Noise at Work", "Protective equipment; hearing protection"],
                 ["Manual Handling and Work at Height", "Lifting loads; working above ground"],
                 ["Electricity at Work", "Safe electrical systems and work"],
                 ["CEMFAW, RIDDOR, COSHH", "Emergency first aid; reporting injuries; hazardous substances"],
             ],
             "notes": "Learners don't need every legal detail: company safe systems of work should already satisfy the law. They should understand why it exists and who is responsible."},
            {"type": "compare", "title": "Responsibilities",
             "left": ("Employees", [
                 "Work safely",
                 "Don't attempt untrained or unauthorised tasks",
                 "Co-operate with the employer",
                 "Don't misuse or interfere with safety provisions",
             ]),
             "right": ("Employers", [
                 "Minimise handling, storage and transport risks",
                 "Provide instruction, training and supervision",
                 "Maintain a safe workplace",
                 "Publish a health and safety policy",
                 "Protect visitors, contractors and the public",
             ])},
            {"type": "cards", "title": "Why it matters",
             "cards": [
                 ("Fewer accidents", "Legislation has reduced accident and incident rates."),
                 ("Wellbeing", "Mental health and wellbeing matter as much as physical safety."),
                 ("Enforcement", "The HSE enforces the law."),
                 ("Non-compliance", "Injury, prosecution, fines, closure and reputational damage."),
             ],
             "notes": "Requirements differ locally, nationally and globally; multinational firms must meet them all."},
        ],
        "quiz": [
            ("Which regulations cover lifting equipment?", "LOLER."),
            ("What does RIDDOR require?", "Reporting of injuries, diseases and dangerous occurrences."),
            ("Name two employee responsibilities.", "Any two, e.g. work safely, co-operate, don't misuse safety equipment."),
            ("Who enforces health and safety law in Great Britain?", "The Health and Safety Executive (HSE)."),
        ],
        "activity": {
            "title": "Legislation match-up",
            "time": "20 minutes",
            "format": "Pairs",
            "steps": [
                "Your teacher gives you ten workshop scenarios.",
                "Match each to the legislation that applies.",
                "Decide who is responsible in each case.",
                "Pick the most serious and explain the consequences of non-compliance.",
            ],
            "success": [
                "Correct legislation named",
                "Responsibilities split correctly",
                "Consequences are realistic",
            ],
        },
        "exit": [
            "Which regulation covers noise from a CNC machine?",
            "Why is wellbeing part of health and safety?",
            "What should you do if asked to use a machine you're not trained on?",
        ],
    },
    {
        "area": "core",
        "file": "core/16-risk-assessment-and-hazardous-contexts.pptx",
        "title": "Risk Assessment and Hazardous Contexts",
        "unit": "Core topic 12",
        "spec": "12.4, 12.5",
        "pages": [P2],
        "objectives": [
            "Identify hazards using HAZOP and HAZID.",
            "Evaluate risk by likelihood, severity and number of people affected.",
            "Apply the hierarchy of control.",
            "Describe safety considerations in specific engineering contexts.",
        ],
        "starter": "Name as many hazards as you can in a machine workshop in 60 seconds.",
        "slides": [
            {"type": "process", "title": "Stages of risk assessment",
             "steps": [
                 ("Identify hazards", "HAZOP, HAZID, inspection."),
                 ("Evaluate risk", "Likelihood, severity, number of people affected."),
                 ("Control", "Apply the hierarchy of control."),
                 ("Record and review", "Document and check it still works."),
             ],
             "notes": "Engineering hazards: equipment, stored energy, tools, electricity, harmful substances and gases, environments."},
            {"type": "process", "title": "The hierarchy of control",
             "steps": [
                 ("Eliminate", "Remove the hazard."),
                 ("Reduce / substitute", "Use something less hazardous."),
                 ("Isolate", "Separate people from the hazard."),
                 ("Engineering controls", "Guards, extraction, interlocks."),
                 ("Administration", "Training, safe systems of work."),
                 ("PPE", "The last resort."),
             ]},
            {"type": "table", "title": "Specific engineering contexts",
             "header": ["Context", "Key considerations"],
             "widths": [2.6, 6],
             "rows": [
                 ["Moving parts", "Guarding, isolation, lock out tag out (LOTO)"],
                 ["Confined spaces", "Asphyxiation, oxygen levels, permit to work, rescue plan"],
                 ["Chemicals", "COSHH, ventilation, fire and explosion risk"],
                 ["Electrical testing and high voltage", "Isolation, permits, stored energy, competent persons"],
                 ["Maintenance", "Safe isolation, heat, manual handling"],
             ]},
        ],
        "quiz": [
            ("What is the first level of the hierarchy of control?", "Elimination."),
            ("Why is PPE the last resort?", "It only protects the wearer and relies on it being worn correctly."),
            ("What is LOTO?", "Lock out tag out: isolating and locking energy sources before work."),
            ("What does a permit to work control?", "Authorisation and conditions for high-risk work."),
        ],
        "activity": {
            "title": "Risk assess the lathe",
            "time": "30 minutes",
            "format": "Small groups",
            "steps": [
                "Risk assess using a centre lathe in the workshop.",
                "Identify at least five hazards.",
                "Score likelihood and severity for each.",
                "Choose controls from as high up the hierarchy as possible.",
            ],
            "success": [
                "Hazards are specific",
                "Scores justified",
                "PPE is not the only control",
            ],
        },
        "exit": [
            "Give an example of an engineering control.",
            "What is HAZOP used for?",
            "Why are confined spaces dangerous?",
        ],
    },
    {
        "area": "core",
        "file": "core/17-environmental-legislation.pptx",
        "title": "Environmental Legislation and Waste",
        "unit": "Core topic 12",
        "spec": "12.6",
        "pages": [P2],
        "objectives": [
            "Describe the main environmental legislation affecting engineering.",
            "Explain the aims and benefits of ISO 14001.",
            "Compare waste disposal methods.",
        ],
        "starter": "Where does the swarf from a milling machine end up? Where should it end up?",
        "slides": [
            {"type": "table", "title": "Environmental legislation",
             "header": ["Legislation", "Purpose"],
             "widths": [3.6, 5],
             "rows": [
                 ["Environmental Protection Act", "Duty of care for waste; controls pollution"],
                 ["Pollution Prevention and Control Act", "Permits for polluting industrial activities"],
                 ["Clean Air Act", "Controls smoke and air pollution"],
                 ["Radioactive Substances Act", "Controls radioactive materials and waste"],
                 ["Controlled, Hazardous Waste and Dangerous Substances rules", "Safe handling, storage and disposal"],
             ]},
            {"type": "compare", "title": "ISO 14001",
             "left": ("Aims and benefits", [
                 "An environmental management system",
                 "Identify and reduce environmental impact",
                 "Comply with the law",
                 "Lower costs and better reputation",
             ]),
             "right": ("If ignored", [
                 "Fines and prosecution",
                 "Lost contracts",
                 "Environmental damage",
                 "Reputational harm",
             ])},
            {"type": "table", "title": "Waste disposal",
             "header": ["Method", "Implications"],
             "widths": [2.4, 6.2],
             "rows": [
                 ["Landfill", "Cheap but harmful and increasingly taxed"],
                 ["Reuse", "Lowest impact; needs planning"],
                 ["Recycling", "Recovers materials such as metal swarf"],
                 ["Controlled waste", "Licensed carriers and records for hazardous waste"],
             ],
             "notes": "Everyone in the organisation shares responsibility for compliance, led by management."},
        ],
        "quiz": [
            ("What does ISO 14001 cover?", "Environmental management systems."),
            ("Which Act controls smoke pollution?", "The Clean Air Act."),
            ("Which disposal method has the lowest environmental impact?", "Reuse."),
            ("What must happen to hazardous waste?", "It must be handled, stored and disposed of by licensed routes with records."),
        ],
        "activity": {
            "title": "Waste audit",
            "time": "20 minutes",
            "format": "Small groups",
            "steps": [
                "List every type of waste your workshop produces.",
                "Classify each as general, recyclable or hazardous.",
                "Suggest the correct disposal route.",
                "Suggest one way to reduce each waste stream.",
            ],
            "success": [
                "Hazardous waste identified",
                "Correct routes chosen",
                "Reduction ideas practical",
            ],
        },
        "exit": [
            "Why is landfill discouraged?",
            "Who is responsible for environmental compliance?",
            "Name one hazardous waste from engineering.",
        ],
    },
    {
        "area": "core",
        "file": "core/18-business-commercial-and-financial-awareness.pptx",
        "title": "Business, Commercial and Financial Awareness",
        "unit": "Core topic 13",
        "spec": "13.1, 13.2, 13.3",
        "pages": [P2],
        "objectives": [
            "Explain commercial priorities, markets and value-added activity.",
            "Describe legal and management practices, including contracts and tendering.",
            "Explain key financial concepts: costs, cash flow, profit and break-even.",
        ],
        "starter": "A part costs 4 pounds to make and sells for 10 pounds. The factory costs 6,000 pounds a month to run. How many must it sell to break even?",
        "slides": [
            {"type": "cards", "title": "Commercial operations",
             "cards": [
                 ("Priorities", "Profit and stakeholder needs."),
                 ("Efficiency", "Value-added activity versus non-value-added activity."),
                 ("Markets", "Local, national and international; supply, demand and competition."),
                 ("Innovation", "R&D keeps products competitive."),
             ],
             "notes": "Starter answer: each part contributes 6 pounds, so 6,000 / 6 = 1,000 parts per month."},
            {"type": "cards", "title": "Business practices",
             "cards": [
                 ("Legal", "Tendering, contracts, warranties, force majeure, indemnity clauses, liabilities."),
                 ("Management", "Resource planning, staffing, training and development."),
                 ("Business models", "Traditional or agile."),
                 ("Systems", "Company management systems, policies and procedures."),
             ]},
            {"type": "table", "title": "Financial concepts",
             "header": ["Term", "Meaning"],
             "widths": [2.6, 6],
             "rows": [
                 ["Direct / indirect costs", "Costs tied to a product (materials) / not tied to one (rent)"],
                 ["Overheads", "Running costs of the business"],
                 ["Cash flow", "Money moving in and out over time"],
                 ["Break-even", "Where revenue equals total costs"],
                 ["Creditors / debtors", "Who you owe / who owes you"],
                 ["Depreciation", "An asset's loss of value over time"],
             ],
             "caption": "Also: sources of finance (loans, shares, capital), budgets, payment terms, profit and loss, solvency, taxes and rates."},
        ],
        "quiz": [
            ("What is break-even?", "The point where revenue equals total costs."),
            ("Is rent a direct or indirect cost?", "Indirect."),
            ("What is force majeure?", "A contract clause covering events outside anyone's control."),
            ("What is a debtor?", "Someone who owes the business money."),
        ],
        "activity": {
            "title": "Price a product",
            "time": "25 minutes",
            "format": "Pairs",
            "steps": [
                "Use the cost data from your teacher for a small engineered product.",
                "Calculate the cost per unit including overheads.",
                "Set a selling price and calculate the break-even quantity.",
                "Explain one risk to your cash flow.",
            ],
            "success": [
                "Costs classified correctly",
                "Break-even calculated",
                "Cash flow risk realistic",
            ],
        },
        "exit": [
            "Give an example of non-value-added activity.",
            "Why can a profitable company run out of cash?",
            "What is a tender?",
        ],
    },
    {
        "area": "core",
        "file": "core/19-professional-conduct-cpd-and-human-factors.pptx",
        "title": "Professional Conduct, CPD and Human Factors",
        "unit": "Core topic 14",
        "spec": "14.1, 14.2, 14.3",
        "pages": [P2],
        "objectives": [
            "Describe expected workplace conduct and levels of accountability.",
            "Explain equality, diversity, accessibility and inclusion duties.",
            "Explain CPD routes and professional recognition.",
            "Explain human factors and how to reduce human error.",
        ],
        "starter": "Most industrial accidents involve human error. Does that mean the workers are to blame?",
        "slides": [
            {"type": "cards", "title": "Professional conduct",
             "cards": [
                 ("Job descriptions", "Set out duties, responsibilities and expected behaviours."),
                 ("Personal conduct", "Reputation, ethics and knowing when to seek advice."),
                 ("Accountability", "Apprentice, operator, management, director."),
                 ("EDAI", "Equality, diversity, accessibility and inclusion duties."),
             ]},
            {"type": "compare", "title": "CPD and professional recognition",
             "left": ("CPD routes", [
                 "Training courses",
                 "Industry placement",
                 "Academic study",
                 "Events and seminars",
             ]),
             "right": ("Why it matters", [
                 "Motivates staff",
                 "Improves performance",
                 "Keeps skills current",
                 "Leads to Engineering Council registration (EngTech, IEng, CEng)",
             ])},
            {"type": "cards", "title": "Human factors",
             "cards": [
                 ("Human characteristics", "Physical and mental capabilities and limits."),
                 ("Workplace design", "Affects safety, comfort and productivity."),
                 ("Causes of error", "Insufficient training, fatigue, workload, stress."),
                 ("Reducing error", "Training, rest breaks, clear procedures, good design, error-proofing."),
             ]},
        ],
        "quiz": [
            ("What is CPD?", "Continuous professional development: ongoing learning throughout a career."),
            ("Who sets professional standards for engineers in the UK?", "The Engineering Council."),
            ("Name two causes of human error.", "Any two of: insufficient training, fatigue, workload, stress."),
            ("What is the purpose of a job description?", "To set out the role's duties and responsibilities."),
        ],
        "activity": {
            "title": "Error-proof the job",
            "time": "25 minutes",
            "format": "Small groups",
            "steps": [
                "Read the incident report from your teacher.",
                "Identify the human factors involved.",
                "Suggest changes to design, training and procedures.",
                "Rank them by how well they prevent a repeat.",
            ],
            "success": [
                "Human factors named correctly",
                "Solutions go beyond blaming the worker",
                "Ranking justified",
            ],
        },
        "exit": [
            "What CPD will you do in the next year?",
            "How can workplace design reduce errors?",
            "Why does reputation matter for an engineer?",
        ],
    },
    {
        "area": "core",
        "file": "core/20-stock-and-asset-management.pptx",
        "title": "Stock and Asset Management",
        "unit": "Core topic 15",
        "spec": "15.1, 15.2",
        "pages": [P2],
        "objectives": [
            "Explain stock management principles.",
            "Compare just-in-time, made-to-stock, made-to-order and MRP.",
            "Describe asset life cycle management and capacity management.",
        ],
        "starter": "A car factory keeps only two hours of parts on site. What are the advantages? What could go wrong?",
        "slides": [
            {"type": "cards", "title": "Stock principles",
             "cards": [
                 ("Demand and turnover", "How fast stock is used and replaced."),
                 ("Cost of inventory", "Money tied up, storage and insurance."),
                 ("Obsolescence", "Redundant stock may have to be written down."),
                 ("Minimum levels", "Safety stock to avoid running out."),
                 ("Supply chain", "Suppliers, packaging and storage."),
             ]},
            {"type": "table", "title": "Stock practices",
             "header": ["Practice", "How it works", "Risk"],
             "widths": [2.2, 3.6, 2.8],
             "rows": [
                 ["Just-in-time", "Parts arrive exactly when needed", "Supply disruption stops production"],
                 ["Made-to-stock", "Build to a forecast and hold stock", "Unsold, obsolete stock"],
                 ["Made-to-order", "Build only when ordered", "Longer lead times"],
                 ["MRP", "Plans material needs from production schedules", "Relies on accurate data"],
             ]},
            {"type": "process", "title": "Asset life cycle",
             "steps": [
                 ("Plan", "Decide what is needed."),
                 ("Acquire", "Buy or build it."),
                 ("Operate and maintain", "Use and look after it."),
                 ("Dispose", "Retire, sell or recycle it."),
             ],
             "caption": "Capacity management (MRP II, finding bottlenecks) and whole-life budgeting, including depreciation, keep assets working efficiently."},
        ],
        "quiz": [
            ("What is just-in-time?", "Receiving parts only when they are needed, with minimal stock."),
            ("What is obsolete stock?", "Stock that can no longer be used or sold."),
            ("What is a bottleneck?", "The stage that limits the capacity of the whole process."),
            ("Name the four asset life cycle stages.", "Plan, acquire, operate and maintain, dispose."),
        ],
        "activity": {
            "title": "Choose a stock strategy",
            "time": "20 minutes",
            "format": "Pairs",
            "steps": [
                "Three businesses: a bespoke furniture maker, a screw manufacturer, a car assembly plant.",
                "Choose a stock practice for each.",
                "Identify the main risk for each.",
                "Suggest how to reduce that risk.",
            ],
            "success": [
                "Practice fits the business",
                "Risks realistic",
                "Mitigations sensible",
            ],
        },
        "exit": [
            "Why hold minimum stock levels?",
            "How does depreciation affect asset decisions?",
            "When is made-to-order the best choice?",
        ],
    },
    {
        "area": "core",
        "file": "core/21-continuous-improvement.pptx",
        "title": "Continuous Improvement",
        "unit": "Core topic 16",
        "spec": "16.1",
        "pages": [P2],
        "objectives": [
            "Explain the PDCA cycle, KPIs, lean and Kaizen.",
            "Identify the 8 wastes.",
            "Describe continuous improvement practices such as 6S, SMED, OEE and TPM.",
        ],
        "starter": "Watch a classmate make a cup of tea (or imagine it). How many unnecessary steps do they take?",
        "slides": [
            {"type": "process", "title": "The PDCA cycle",
             "steps": [
                 ("Plan", "Identify the problem and plan a change."),
                 ("Do", "Try it on a small scale."),
                 ("Check", "Measure results against KPIs."),
                 ("Act", "Adopt, adjust or abandon, then repeat."),
             ],
             "caption": "Kaizen means small, continuous, incremental improvements by everyone."},
            {"type": "cards", "title": "The 8 wastes",
             "cards": [
                 ("Transportation", "Moving materials unnecessarily."),
                 ("Inventory", "Too much stock."),
                 ("Motion", "People moving more than needed."),
                 ("Waiting", "Idle time."),
                 ("Over-production and over-processing", "Making too much, or doing more than required."),
                 ("Defects and unused talent", "Scrap and rework; not using people's skills."),
             ]},
            {"type": "table", "title": "Improvement practices",
             "header": ["Practice", "Purpose"],
             "widths": [2.6, 6],
             "rows": [
                 ["Value stream mapping", "Map every step to find waste"],
                 ["Visual management and kanban", "Make status and demand visible at a glance"],
                 ["6S", "Sort, set in order, shine, standardise, sustain, safety"],
                 ["SMED", "Single minute exchange of dies: faster changeovers"],
                 ["OEE", "Overall equipment effectiveness = availability x performance x quality"],
                 ["TPM", "Total productive maintenance: operators help maintain machines"],
             ]},
        ],
        "quiz": [
            ("What does PDCA stand for?", "Plan, do, check, act."),
            ("Name four of the 8 wastes.", "Any four, e.g. transportation, inventory, motion, waiting."),
            ("What does SMED reduce?", "Changeover time."),
            ("A machine is 90% available, 80% performance and 95% quality. OEE?", "About 68%."),
        ],
        "activity": {
            "title": "Lean the process",
            "time": "30 minutes",
            "format": "Small groups",
            "steps": [
                "Map the value stream of a simple workshop task.",
                "Mark every waste using the 8 wastes.",
                "Apply 6S to the work area.",
                "Plan one PDCA cycle to test an improvement.",
            ],
            "success": [
                "At least five wastes identified",
                "6S steps applied",
                "PDCA plan has a measurable KPI",
            ],
        },
        "exit": [
            "Which waste is most common in your workshop?",
            "Why use KPIs in continuous improvement?",
            "What is the difference between Kaizen and a big one-off change?",
        ],
    },
    {
        "area": "core",
        "file": "core/22-project-management.pptx",
        "title": "Project and Programme Management",
        "unit": "Core topic 17",
        "spec": "17.1, 17.2, 17.3",
        "pages": [P2],
        "objectives": [
            "Describe the project life cycle, constraints and risk management.",
            "Describe project roles and responsibilities.",
            "Plan a project using Gantt charts, CPA and PERT.",
            "Monitor and control a project by stages and by exception.",
        ],
        "starter": "Building a bridge involves hundreds of tasks. How would you know which ones can't be allowed to slip?",
        "slides": [
            {"type": "process", "title": "The project life cycle",
             "steps": [
                 ("Initiate", "Brief, goals and success criteria."),
                 ("Plan", "Resources, schedule, risks."),
                 ("Implement", "Do the work."),
                 ("Monitor", "Track against the plan."),
                 ("Report", "Keep stakeholders informed."),
                 ("Evaluate", "Review and learn."),
             ],
             "notes": "Constraints: budget, cost, quality, time, safety, resources, communication, reputation, changing requirements. Collaborative working includes matrix working and collaborative technologies."},
            {"type": "cards", "title": "Roles",
             "cards": [
                 ("Stakeholders", "Clients, regulators and others with an interest."),
                 ("Project manager", "Plans, monitors and controls the project."),
                 ("Team members", "Deliver the tasks and report progress."),
                 ("Responsibilities", "Communication, monitoring, planning, finance, reporting."),
             ]},
            {"type": "compare", "title": "Planning and control",
             "left": ("Planning tools", [
                 "Gantt charts: tasks on a timeline",
                 "Critical path analysis: the longest chain of dependent tasks",
                 "PERT: optimistic, likely and pessimistic estimates",
                 "Contingency planning and managing interdependencies",
             ]),
             "right": ("Control methods", [
                 "Monitoring reports: budget, quality, cost, time",
                 "Managing by stages: approve each stage before the next",
                 "Managing by exception: escalate only when limits are exceeded",
             ])},
        ],
        "quiz": [
            ("What happens if a critical path task is delayed?", "The whole project is delayed."),
            ("What is managing by exception?", "Only escalating issues when agreed tolerances are exceeded."),
            ("What does PERT use for time estimates?", "Optimistic, most likely and pessimistic estimates."),
            ("Name three project constraints.", "Any three, e.g. budget, time, quality."),
        ],
        "activity": {
            "title": "Plan a workshop project",
            "time": "30 minutes",
            "format": "Pairs",
            "steps": [
                "Tasks: design (3 days), order parts (5), machine parts (4), assemble (2), test (1). Machining can't start until parts arrive.",
                "Draw a Gantt chart.",
                "Find the critical path and total duration.",
                "Write one contingency plan.",
            ],
            "success": [
                "Dependencies correct",
                "Critical path identified",
                "Contingency is realistic",
            ],
            "notes": "If ordering can start during design, the path is order, machine, assemble, test = 12 days; if it waits for design, 15 days. Discuss both.",
        },
        "exit": [
            "Why involve regulators as stakeholders?",
            "What is float?",
            "When would you manage by stages?",
        ],
    },
    {
        "area": "core",
        "file": "core/23-employer-set-project.pptx",
        "title": "The Employer-set Project",
        "unit": "Core Component",
        "spec": "Employer-set Project",
        "pages": [ESP],
        "objectives": [
            "Explain the weighting and conditions of the Employer-set Project.",
            "Describe the research, design, plan and present tasks.",
            "Explain the five assessment objectives and how to target them.",
        ],
        "starter": "The ESP brief is complex and non-routine. What does 'non-routine' mean, and how can you prepare for something you haven't seen?",
        "slides": [
            {"type": "bullets", "title": "What is the ESP?",
             "bullets": [
                 "30% of the core, with 18.5 hours of assessment time.",
                 "Externally set and marked by City & Guilds.",
                 "A realistic industry brief developed with employers.",
                 "Draws on knowledge from across the whole engineering core.",
                 "Linked to four core skills: planning and preparation, communication, develop and manufacture, evaluation.",
             ],
             "callout": "Specialism knowledge is assessed separately. The ESP is about applying the core."},
            {"type": "process", "title": "The tasks",
             "steps": [
                 ("Research", "Investigate the brief."),
                 ("Design", "Develop a solution."),
                 ("Plan", "Plan how it would be made."),
                 ("Present", "Present your outcome."),
             ]},
            {"type": "table", "title": "Assessment objectives",
             "header": ["AO", "Focus", "Weight"],
             "widths": [0.9, 6.6, 1.1],
             "rows": [
                 ["AO1", "Plan your approach: planned, sequenced, prioritised, iterative", "13%"],
                 ["AO2", "Apply core knowledge and skills in the context of the brief", "50%"],
                 ["AO3", "Select and use relevant techniques and resources", "13%"],
                 ["AO4", "Use maths, English and digital skills correctly", "10%"],
                 ["AO5", "Realise the outcome and review how well it meets the brief", "13%"],
             ],
             "caption": "AO2 is half the marks: link your knowledge explicitly to the brief."},
        ],
        "quiz": [
            ("What percentage of the core is the ESP?", "30%."),
            ("Which AO carries the most marks?", "AO2, applying core knowledge and skills (50%)."),
            ("Name the four task areas.", "Research, design, plan, present."),
            ("What does AO5 ask for?", "Realising the outcome and reviewing how well it meets the brief."),
        ],
        "activity": {
            "title": "Mini brief",
            "time": "40 minutes",
            "format": "Small groups",
            "steps": [
                "Brief: design a wall bracket to hold a 15 kg shelf in a damp garage.",
                "Research: list the core topics that apply.",
                "Design: sketch a solution and choose a material.",
                "Plan and present: outline manufacture and give a two-minute pitch.",
            ],
            "success": [
                "Links to at least four core topics",
                "Material justified for damp conditions",
                "Calculations and units used",
            ],
        },
        "exit": [
            "Which AO do you think you would score lowest on, and why?",
            "How can you show iteration in your approach?",
            "Why consider rejected options in your review?",
        ],
    },
]
