"""Mechanical Engineering occupational specialism decks."""

KNOW = "02-occupational-specialism/01-knowledge-criteria.md"
PRAC = "02-occupational-specialism/02-practical-criteria.md"

DECKS = [
    # ---------------------------------------------------------- knowledge
    {
        "area": "spec",
        "file": "specialism/01-design-principles-methodologies-and-verification.pptx",
        "title": "Design Principles, Methodologies and Verification",
        "unit": "Mechanical: Knowledge criteria",
        "spec": "1.1, 1.2, 1.8",
        "pages": [KNOW],
        "objectives": [
            "Identify, record and develop client requirements.",
            "Compare systems, sub-assembly and component-by-component methodologies.",
            "Explain DFM/DFA, planned obsolescence and anthropometric data.",
            "Distinguish verification from validation.",
        ],
        "starter": "A client asks for 'a better wheelbarrow'. What do you need to find out before you draw anything?",
        "slides": [
            {"type": "cards", "title": "Principles of engineering design",
             "cards": [
                 ("Requirements", "Function, aesthetics, dimensions, ergonomics, safety, sustainability, cost, materials."),
                 ("Identifying them", "Market research, client interviews and observation, product analysis."),
                 ("Recording them", "Design briefs, specifications, questionnaires, observational records."),
                 ("Communicating designs", "Orthographic drawings, virtual models, physical models."),
             ],
             "notes": "Fields within mechanical engineering: design; manufacture and processing; fitting and assembly maintenance."},
            {"type": "table", "title": "Design methodologies",
             "header": ["Methodology", "Approach", "Suits"],
             "widths": [2.4, 3.6, 2.6],
             "rows": [
                 ["Systems approach", "Design the whole system and how parts interact", "Complex products"],
                 ["Sub-assembly", "Design groups of parts as units", "Modular products"],
                 ["Component by component", "Design each part individually", "Simple or bespoke items"],
             ],
             "caption": "DFM/DFA: process capability and tolerances decide what can be made and assembled economically."},
            {"type": "compare", "title": "Verification and validation",
             "left": ("Verification", [
                 "Did we build it right?",
                 "Checks the design against the specification",
                 "Comparison matrices, functional tests, measurement",
             ]),
             "right": ("Validation", [
                 "Did we build the right thing?",
                 "Checks it meets the user's real needs",
                 "User testing, ranking, decision trees",
             ])},
        ],
        "quiz": [
            ("Name three ways to identify client requirements.", "Market research, client interviews/observation, product analysis."),
            ("What is anthropometric data used for?", "Designing products to fit human body sizes (ergonomics)."),
            ("What is planned obsolescence?", "Designing a product to have a limited life."),
            ("Is checking a part against its drawing verification or validation?", "Verification."),
        ],
        "activity": {
            "title": "Better wheelbarrow",
            "time": "30 minutes",
            "format": "Pairs",
            "steps": [
                "Interview your partner as the client and record their requirements.",
                "Write a specification with measurable criteria.",
                "Use an anthropometric table to size the handles.",
                "Build a comparison matrix to verify one concept against the specification.",
            ],
            "success": [
                "Requirements are measurable",
                "Anthropometric data used correctly",
                "Matrix scores justified",
            ],
        },
        "exit": [
            "Which methodology suits a gearbox, and why?",
            "Why can't you skip validation?",
            "How do tolerances affect DFA?",
        ],
    },
    {
        "area": "spec",
        "file": "specialism/02-mechanical-drawings-standards-and-communication.pptx",
        "title": "Mechanical Drawings, Standards and Communication",
        "unit": "Mechanical: Knowledge criteria",
        "spec": "1.3, 1.4, 1.20",
        "pages": [KNOW],
        "objectives": [
            "Interpret orthographic drawings, sections and standard features.",
            "Explain the role of BSI, ISO and IMechE.",
            "Choose methods and formats to communicate engineering information.",
            "Explain CAD to CAM transfer and the uses of 2D, 3D and CAE tools.",
        ],
        "starter": "How would you explain the design of a gear to a machinist, a customer and a manager? Would you use the same drawing?",
        "slides": [
            {"type": "cards", "title": "Mechanical drawings",
             "cards": [
                 ("Orthographic drawings", "Sheet sizes, views, section views and hatching."),
                 ("Standard features", "Springs, splines, gears, webs, solid shafts, keys and keyways."),
                 ("Symbols", "Balloons, diameter, depth, per BS EN 8888."),
             ]},
            {"type": "cards", "title": "Standards bodies",
             "cards": [
                 ("BSI", "British Standards Institution: UK standards."),
                 ("ISO", "International Organization for Standardization."),
                 ("IMechE", "Institution of Mechanical Engineers: professional codes and guidance."),
             ],
             "notes": "Learners should know how to access and interpret regulatory requirements for mechanical component design."},
            {"type": "compare", "title": "Communicating engineering information",
             "left": ("Methods", [
                 "CAD models and engineering drawings",
                 "Specifications, SOPs and reports",
                 "Presentations",
                 "Graphs of performance data and SPC",
                 "Sending programs to CNC machines",
             ]),
             "right": ("Audiences", [
                 "Designers",
                 "Manufacturing engineers",
                 "Customers",
                 "Non-technical personnel",
             ])},
            {"type": "cards", "title": "Digital tools",
             "cards": [
                 ("2D CAD", "Fast, clear drawings for manufacture."),
                 ("3D CAD", "Solid models, assemblies and clash checks."),
                 ("CAD to CAM", "Toolpaths sent by direct entry, intranet or Wi-Fi to CNC machines."),
                 ("CAE and visualisation", "Simulate assembly performance; render for customers."),
             ]},
        ],
        "quiz": [
            ("Which standard covers technical drawings?", "BS EN 8888."),
            ("What does a section view show?", "The inside of a part as if cut through, with hatching."),
            ("What is CAE used for?", "Simulating and analysing how a design will perform."),
            ("Who is IMechE?", "The Institution of Mechanical Engineers."),
        ],
        "activity": {
            "title": "Three audiences",
            "time": "30 minutes",
            "format": "Small groups",
            "steps": [
                "Take a simple component such as a shaft with a keyway.",
                "Produce a detailed drawing for the machinist.",
                "Produce a visual for the customer.",
                "Write a one-paragraph summary for a manager.",
            ],
            "success": [
                "Drawing follows BS EN 8888",
                "Customer visual has no jargon",
                "Summary is concise",
            ],
        },
        "exit": [
            "When is 2D CAD better than 3D?",
            "What is a keyway for?",
            "How does data get from CAD to a CNC machine?",
        ],
    },
    {
        "area": "spec",
        "file": "specialism/03-simple-machines-and-mechanical-calculations.pptx",
        "title": "Simple Machines and Mechanical Calculations",
        "unit": "Mechanical: Knowledge criteria",
        "spec": "1.5, 1.6, 1.13",
        "pages": [KNOW],
        "objectives": [
            "Describe gears, pulleys, levers, linkages, cams and ratchets.",
            "Calculate gear ratios for simple and compound gear trains.",
            "Calculate mechanical advantage, velocity ratio and efficiency.",
            "Apply stress, strain and beam calculations to design.",
        ],
        "starter": "A bike's pedal gear has 48 teeth and the rear gear has 16. How many times does the wheel turn for each pedal turn?",
        "slides": [
            {"type": "cards", "title": "Simple machines",
             "cards": [
                 ("Gears", "Spur, helical, bevel, worm, rack and pinion."),
                 ("Levers", "Class 1 (seesaw), class 2 (wheelbarrow), class 3 (tweezers)."),
                 ("Linkages", "Reverse motion, parallel motion, bell crank, crank and slider."),
                 ("Cams", "Circular, eccentric and snail (drop) cams turn rotary into reciprocating motion."),
                 ("Pulleys and ratchets", "Change force direction; allow motion one way only."),
             ],
             "notes": "Each machine changes the magnitude, direction or type of motion."},
            {"type": "bullets", "title": "Gear trains",
             "bullets": [
                 "Gear ratio = teeth on driven gear / teeth on driver gear.",
                 "Output speed = input speed / gear ratio.",
                 "Compound train: multiply the ratios of each pair.",
                 "Starter: 16 / 48 = 1/3, so the wheel turns 3 times per pedal turn.",
             ],
             "callout": "A ratio above 1 slows the output and increases torque. Below 1 speeds it up and reduces torque."},
            {"type": "table", "title": "Machine performance",
             "header": ["Quantity", "Formula"],
             "widths": [3, 5.6],
             "rows": [
                 ["Mechanical advantage (MA)", "Load / effort"],
                 ["Velocity ratio (VR)", "Distance moved by effort / distance moved by load"],
                 ["Efficiency", "MA / VR x 100%"],
                 ["Work", "Force x distance"],
                 ["Power", "Work / time"],
             ]},
            {"type": "table", "title": "Force calculations",
             "header": ["Quantity", "Formula"],
             "widths": [3, 5.6],
             "rows": [
                 ["Stress", "Force / area"],
                 ["Strain", "Extension / original length"],
                 ["Young's modulus", "Stress / strain"],
                 ["Beam reactions", "Take moments about a support; reactions sum to the total load"],
                 ["Material quantity and cost", "Area or volume x unit cost, plus manufacturing cost"],
             ],
             "notes": "Beams can be simply supported or cantilevered; learners calculate reactions, shear force and bending moment."},
        ],
        "quiz": [
            ("A 20-tooth driver meshes with a 60-tooth driven gear. Gear ratio?", "3:1."),
            ("If the driver turns at 900 rpm, what is the output speed?", "300 rpm."),
            ("A pulley lifts 400 N with 100 N effort. MA?", "4."),
            ("If VR is 5 and MA is 4, what is the efficiency?", "80%."),
            ("Which lever class is a wheelbarrow?", "Class 2."),
        ],
        "activity": {
            "title": "Design a winch",
            "time": "35 minutes",
            "format": "Pairs",
            "steps": [
                "A winch must lift 2,000 N using a 250 N effort.",
                "Design a compound gear train to achieve it.",
                "Calculate MA, VR and efficiency assuming 80% efficiency.",
                "Suggest where a ratchet is needed and why.",
            ],
            "success": [
                "Gear ratio calculated correctly",
                "Efficiency accounted for",
                "Ratchet placement justified",
            ],
        },
        "exit": [
            "Why can't efficiency ever reach 100%?",
            "Which gear type changes the axis by 90 degrees?",
            "What does a cam follower do?",
        ],
    },
    {
        "area": "spec",
        "file": "specialism/04-loads-environment-and-aerodynamics.pptx",
        "title": "Loads, Environment and Aerodynamics in Design",
        "unit": "Mechanical: Knowledge criteria",
        "spec": "1.7, 1.12",
        "pages": [KNOW],
        "objectives": [
            "Describe types of mechanical load and their effects.",
            "Explain how service and environmental conditions affect materials.",
            "Interpret 2D fluid flow diagrams.",
            "Explain how lift, drag, thrust and turbulence load structures.",
        ],
        "starter": "Why do tall chimneys often have a spiral fin wrapped around them?",
        "slides": [
            {"type": "cards", "title": "Mechanical loads",
             "cards": [
                 ("Static and dynamic", "Steady loads versus changing or moving loads."),
                 ("Point and uniform", "Load at one spot versus spread along a length."),
                 ("Torque and shear", "Twisting and sliding forces."),
                 ("Bending moments", "Loads that bend a member."),
                 ("Fatigue", "Repeated loading that causes cracking over time."),
             ],
             "notes": "Starter answer: the helical strake breaks up vortices so wind doesn't make the chimney oscillate."},
            {"type": "cards", "title": "Service and environmental conditions",
             "cards": [
                 ("Chemical attack", "Corrosion reduces strength over time."),
                 ("Temperature", "Heat softens and expands; cold makes some materials brittle."),
                 ("Functional properties", "The design must keep working in its environment."),
                 ("Other factors", "Manufacturing method and material choice shape the outcome."),
             ]},
            {"type": "compare", "title": "Aerodynamics",
             "left": ("Fluid flow", [
                 "Laminar: smooth parallel layers",
                 "Turbulent: chaotic mixing",
                 "Separation points: where flow leaves the surface",
                 "Vortices: swirling flow behind objects",
             ]),
             "right": ("Forces on structures", [
                 "Lift: at right angles to flow",
                 "Drag: opposes motion",
                 "Thrust: drives forward",
                 "Turbulence: fluctuating loads that can cause fatigue",
             ])},
        ],
        "quiz": [
            ("What is a uniformly distributed load?", "A load spread evenly along a length."),
            ("What causes fatigue?", "Repeated or cyclic loading."),
            ("Where does turbulent flow usually start on a blunt object?", "At the separation point."),
            ("Why can vortices damage structures?", "They create fluctuating forces that cause vibration and fatigue."),
        ],
        "activity": {
            "title": "Load a sign post",
            "time": "25 minutes",
            "format": "Pairs",
            "steps": [
                "A road sign on a post faces strong winds by the sea.",
                "Identify every load acting on it.",
                "Identify the environmental conditions and their effects.",
                "Suggest two design changes to cope.",
            ],
            "success": [
                "Wind, weight and fatigue loads identified",
                "Corrosion considered",
                "Changes justified",
            ],
        },
        "exit": [
            "Give an example of a dynamic load.",
            "How does temperature affect a polymer?",
            "Why do racing cars have wings?",
        ],
    },
    {
        "area": "spec",
        "file": "specialism/05-business-context-constraints-and-metrics.pptx",
        "title": "Business Context, Constraints and Metrics in Design",
        "unit": "Mechanical: Knowledge criteria",
        "spec": "1.9",
        "pages": [KNOW],
        "objectives": [
            "Explain market pull and technology push.",
            "Describe commercial and operational constraints on design.",
            "Calculate manufacturing cost and profit.",
            "Explain how commercial risk analysis affects design review.",
        ],
        "starter": "Was the smartphone created because people asked for it, or because the technology became possible?",
        "slides": [
            {"type": "compare", "title": "Context",
             "left": ("Market pull", [
                 "Customers create demand",
                 "Designs respond to a known need",
                 "e.g. a lighter power tool",
             ]),
             "right": ("Technology push", [
                 "New technology creates the opportunity",
                 "Designs find a market for it",
                 "e.g. the first 3D printers",
             ]),
             "notes": "Also: commercial advantage, design for reuse, planned obsolescence and sustainability."},
            {"type": "cards", "title": "Constraints",
             "cards": [
                 ("Commercial", "Competition and profitability."),
                 ("Operational", "Tools, equipment, materials, process capability, people and training."),
                 ("Legal", "Regulations and confidentiality."),
                 ("Manufacture", "Design for manufacture."),
             ]},
            {"type": "table", "title": "Cost and profit",
             "header": ["Item", "Example per unit"],
             "widths": [4, 4.6],
             "rows": [
                 ["Materials", "3.00 pounds"],
                 ["Labour", "4.50 pounds"],
                 ["Overheads", "2.50 pounds"],
                 ["Total manufacturing cost", "10.00 pounds"],
                 ["Selling price", "14.00 pounds"],
                 ["Profit per unit", "4.00 pounds"],
             ],
             "caption": "Metrics: budget, cost, profit and time. Commercial risk analysis feeds project design reviews."},
        ],
        "quiz": [
            ("Is a customer-requested feature market pull or technology push?", "Market pull."),
            ("Name the three parts of manufacturing cost.", "Materials, labour, overheads."),
            ("A part costs 8 pounds to make and sells for 11. Profit per unit?", "3 pounds."),
            ("Give one operational constraint.", "E.g. tools, equipment, process capability, training."),
        ],
        "activity": {
            "title": "Cost a design",
            "time": "25 minutes",
            "format": "Pairs",
            "steps": [
                "Use the material and labour data from your teacher for a steel bracket.",
                "Calculate the total manufacturing cost per unit.",
                "Set a selling price for a 25% profit margin.",
                "Identify one constraint and how to overcome it.",
            ],
            "success": [
                "All three cost elements included",
                "Price calculation correct",
                "Constraint solution realistic",
            ],
        },
        "exit": [
            "Give an example of technology push.",
            "Why might a company accept a lower profit?",
            "How can a constraint be overcome?",
        ],
    },
    {
        "area": "spec",
        "file": "specialism/06-materials-standard-parts-and-processes.pptx",
        "title": "Materials, Standard Parts and Manufacturing Processes",
        "unit": "Mechanical: Knowledge criteria",
        "spec": "1.10, 1.11",
        "pages": [KNOW],
        "objectives": [
            "Select materials using fitness for purpose, availability, risk and factor of safety.",
            "Explain why standard parts are used.",
            "Compare wasting, shaping, forming, welding, 3D printing and joining processes.",
            "Explain why tolerances and fits matter for assembly.",
        ],
        "starter": "Why don't companies make their own nuts and bolts?",
        "slides": [
            {"type": "cards", "title": "Choosing materials",
             "cards": [
                 ("Fitness for purpose", "Properties that meet the function."),
                 ("Availability", "Standard stock forms and lead times."),
                 ("Risk", "Consequences if it fails."),
                 ("Factor of safety", "Design for more load than expected, e.g. 2 x the working load."),
             ],
             "notes": "Families: ferrous and non-ferrous metals, thermoplastics (ABS, HIPS, PLA, polycarbonate, polypropylene, acrylic), thermosets, elastomers, composites, ceramics and smart materials."},
            {"type": "bullets", "title": "Standard parts",
             "bullets": [
                 "Examples: valves, sensors, piping, supports and fittings.",
                 "Cheaper than making your own.",
                 "Proven quality and known performance.",
                 "Easy to replace and source.",
             ],
             "callout": "Design around standard parts wherever you can. It cuts cost and lead time."},
            {"type": "table", "title": "Manufacturing processes",
             "header": ["Process", "Examples", "Trade-off"],
             "widths": [1.8, 3.2, 3.6],
             "rows": [
                 ["Wasting", "Cutting, filing, turning, milling, grinding", "Accurate, but wastes material"],
                 ["Shaping", "Casting, moulding", "Complex shapes, high tooling cost"],
                 ["Forming", "Bending, pressing", "Fast, little waste, needs ductile material"],
                 ["Welding", "MIG/MAG, TIG", "Strong permanent joints, heat distortion"],
                 ["3D printing", "Additive layers", "Complex one-offs, slow for volume"],
                 ["Joining and finishing", "Fixings, adhesives, coatings, assembly", "Varies with method"],
             ]},
        ],
        "quiz": [
            ("What is a factor of safety?", "The ratio of a design's strength to the load it is expected to carry."),
            ("Why use standard parts?", "Cheaper, proven, easy to replace and source."),
            ("Which welding process suits thin stainless steel with a neat finish?", "TIG."),
            ("Why do tolerances matter for assembly?", "Parts must fit together as intended."),
        ],
        "activity": {
            "title": "Process selection",
            "time": "25 minutes",
            "format": "Pairs",
            "steps": [
                "Three parts: a one-off prototype bracket, 10,000 plastic clips, and a steel frame.",
                "Choose a material and process for each.",
                "Name any standard parts you would buy in.",
                "Justify each choice.",
            ],
            "success": [
                "Process suits the quantity",
                "Material suits the function",
                "Standard parts sensibly used",
            ],
        },
        "exit": [
            "When is 3D printing the best process?",
            "What is the difference between MIG and TIG?",
            "Why choose a polymer over a metal?",
        ],
    },
    {
        "area": "spec",
        "file": "specialism/07-quality-testing-and-measurement.pptx",
        "title": "Quality, Testing and Measurement",
        "unit": "Mechanical: Knowledge criteria",
        "spec": "1.15, 1.17, 1.18, 1.19",
        "pages": [KNOW],
        "objectives": [
            "Distinguish assignable from random causes of error.",
            "Compare quality assurance and quality control, and sampling with 100% inspection.",
            "Compare non-destructive and destructive testing methods.",
            "Choose measurement equipment and analyse measurement data statistically.",
        ],
        "starter": "Two operators measure the same part and get different results. List every reason why.",
        "slides": [
            {"type": "compare", "title": "Causes of error",
             "left": ("Assignable (systematic)", [
                 "Faulty calibration",
                 "Tool wear",
                 "Observer bias",
                 "Human error",
                 "Can be found and fixed",
             ]),
             "right": ("Random", [
                 "Ambient conditions",
                 "Temperature and humidity",
                 "Instrument uncertainty",
                 "Reduced, not eliminated",
             ]),
             "notes": "Quality assurance: procedures, calibration, process capability monitoring, preventative maintenance. Quality control: testing and inspection. Production quantity decides between sampling and 100% inspection."},
            {"type": "table", "title": "Testing methods",
             "header": ["Type", "Method", "Detects"],
             "widths": [1.8, 3, 3.8],
             "rows": [
                 ["Non-destructive", "Visual, measurement, go/no-go gauges", "Surface and dimensional faults"],
                 ["Non-destructive", "Ultrasonic, X-radiography", "Internal flaws"],
                 ["Non-destructive", "Penetrant, magnetic particle", "Surface cracks"],
                 ["Destructive", "Tensile, hardness", "Strength and hardness"],
                 ["Destructive", "Impact (Izod, Charpy), macro examination", "Toughness and internal structure"],
             ]},
            {"type": "table", "title": "Measurement equipment",
             "header": ["Equipment", "Use"],
             "widths": [3, 5.6],
             "rows": [
                 ["Rules, protractors", "Basic length and angle"],
                 ["Vernier and digital callipers", "Inside, outside and depth"],
                 ["Micrometers (outside, inside, depth)", "Precise small dimensions"],
                 ["Gauges (go/no-go, slip, plug)", "Quick pass or fail checks; reference lengths"],
                 ["DTI, CMM, laser scanning", "Run-out, complex 3D geometry"],
                 ["Digital stress/strain machines", "Mechanical properties"],
             ],
             "caption": "Analyse results with mean, range and standard deviation to judge whether parts are in tolerance."},
        ],
        "quiz": [
            ("Is tool wear an assignable or random cause?", "Assignable."),
            ("Which test finds internal flaws without damaging the part?", "Ultrasonic testing or X-radiography."),
            ("What does a Charpy test measure?", "Toughness (impact energy absorbed)."),
            ("What does a go/no-go gauge do?", "Quickly checks whether a feature is within limits."),
        ],
        "activity": {
            "title": "Is the batch in tolerance?",
            "time": "30 minutes",
            "format": "Pairs, practical",
            "steps": [
                "Measure ten parts with a micrometer.",
                "Calculate the mean, range and standard deviation.",
                "Compare with the drawing tolerance.",
                "Decide whether the process needs adjusting and suggest a cause.",
            ],
            "success": [
                "Measurements recorded correctly",
                "Statistics accurate",
                "Decision justified",
            ],
        },
        "exit": [
            "When would you use destructive testing?",
            "Why calibrate measuring equipment?",
            "What does a large standard deviation tell you?",
        ],
    },
    {
        "area": "spec",
        "file": "specialism/08-installation-and-integration.pptx",
        "title": "Installation and Integration of Systems",
        "unit": "Mechanical: Knowledge criteria",
        "spec": "1.16",
        "pages": [KNOW],
        "objectives": [
            "Describe the requirements for installing mechanical systems.",
            "Describe the stages of system integration.",
            "Explain how sub-systems become one functioning system.",
        ],
        "starter": "A new conveyor arrives in pieces from three suppliers. What must happen before it can run?",
        "slides": [
            {"type": "cards", "title": "Installation requirements",
             "cards": [
                 ("Customer requirements", "What the system must do on site."),
                 ("Regulatory requirements", "Safety law and standards."),
                 ("Manufacturer specifications", "Mounting, alignment, torque settings, clearances."),
             ]},
            {"type": "process", "title": "Integrating systems",
             "steps": [
                 ("Plan", "Define interfaces and sequence."),
                 ("Combine", "Bring sub-systems together."),
                 ("Connect functions", "Mechanical, electrical and control links."),
                 ("Test", "Check each interface, then the whole."),
                 ("Commission", "Prove it works as specified."),
             ]},
        ],
        "quiz": [
            ("Name three sources of installation requirements.", "Customer, regulatory, manufacturer specifications."),
            ("What is an interface in system integration?", "A point where two sub-systems connect or interact."),
            ("Why test interfaces before the whole system?", "Faults are easier to find and fix."),
        ],
        "activity": {
            "title": "Integration plan",
            "time": "20 minutes",
            "format": "Pairs",
            "steps": [
                "Take the conveyor from the starter.",
                "List its sub-systems and interfaces.",
                "Put the integration steps in order.",
                "Write a test for each interface.",
            ],
            "success": [
                "All interfaces identified",
                "Logical sequence",
                "Tests are specific",
            ],
        },
        "exit": [
            "Why follow the manufacturer's torque settings?",
            "What happens during commissioning?",
            "Who needs to sign off an installation?",
        ],
    },
    # ---------------------------------------------------------- practical
    {
        "area": "spec",
        "file": "specialism/09-analysing-requirements-and-design-information.pptx",
        "title": "Analysing Requirements and Design Information",
        "unit": "Mechanical: Performance Outcome 2",
        "spec": "Outcome 2 (2.1 to 2.5)",
        "pages": [PRAC],
        "objectives": [
            "Interpret design briefs, specifications and stakeholder information.",
            "Evaluate materials, timescales, costs and risks for a project.",
            "Find and correct errors in engineering information and manage scope creep.",
            "Verify designs using calculations, CAD simulation and physical models.",
        ],
        "starter": "Halfway through a project, the client asks for 'just one more small feature'. What's the risk?",
        "slides": [
            {"type": "cards", "title": "Accessing and evaluating information",
             "cards": [
                 ("Sources", "Design briefs, specifications, concept drawings, stakeholders."),
                 ("Evaluating a project", "Materials, manufacturing timescale, cost and risks with mitigation."),
                 ("Formats", "Specifications, CAD models, drawings, process diagrams, SOPs, production plans."),
                 ("Errors", "Spot inaccuracies, correct them, escalate when needed."),
             ]},
            {"type": "bullets", "title": "Scope creep and design change",
             "bullets": [
                 "Scope creep: requirements grow without control.",
                 "Process-driven change: manufacturing limits force a redesign.",
                 "Record every change and its impact on cost and time.",
                 "Escalate or report changes that affect the agreed brief.",
             ],
             "callout": "Every 'small' change costs time and money. Log it before you act on it."},
            {"type": "cards", "title": "Verifying design information",
             "cards": [
                 ("Against requirements", "Components, materials, application, location, risk, environment."),
                 ("Calculations", "Check loads, stresses and performance."),
                 ("CAD simulation", "Test the design virtually."),
                 ("Physical models", "Check fit, form and function."),
             ]},
        ],
        "quiz": [
            ("What is scope creep?", "Uncontrolled growth in project requirements."),
            ("Give two formats of engineering information.", "Any two, e.g. specifications, CAD models, drawings, SOPs."),
            ("Why verify a design with calculations as well as CAD?", "To check the simulation and confirm results independently."),
        ],
        "activity": {
            "title": "Spot the errors",
            "time": "25 minutes",
            "format": "Pairs",
            "steps": [
                "Review the drawing and specification pack from your teacher.",
                "Find at least four errors or inconsistencies.",
                "Correct each one.",
                "Decide which ones need escalating and to whom.",
            ],
            "success": [
                "Errors found and corrected",
                "Escalation decisions justified",
                "Changes recorded",
            ],
        },
        "exit": [
            "Who should you tell about an error in a drawing?",
            "How would you control scope creep?",
            "Which verification method is cheapest?",
        ],
    },
    {
        "area": "spec",
        "file": "specialism/10-evaluating-and-improving-designs.pptx",
        "title": "Evaluating and Improving Designs",
        "unit": "Mechanical: Performance Outcome 3",
        "spec": "Outcome 3 (3.1 to 3.9)",
        "pages": [PRAC],
        "objectives": [
            "Select tools to model and evaluate design performance.",
            "Analyse factors affecting designs and justify material choices.",
            "Use degradation knowledge and test results to evaluate proposals.",
            "Compare design options and respond constructively to feedback.",
        ],
        "starter": "Is it better to improve an existing design or start from scratch? When would you do each?",
        "slides": [
            {"type": "cards", "title": "Modelling and analysis",
             "cards": [
                 ("Tools", "Mathematical models, spreadsheets, CAD simulations."),
                 ("Choosing a tool", "Cost, availability, compatibility, training needs, time, failure modes."),
                 ("Design factors", "Materials, application, location, risk, environment, configuration, geometry, scale."),
                 ("Optimise or develop", "Improving an existing design versus creating a new one."),
             ]},
            {"type": "cards", "title": "Materials, failure and testing",
             "cards": [
                 ("Justify materials", "Use property data and the context."),
                 ("Degradation", "Corrosion, fracture, abrasion, creep and fatigue, and how to prevent them."),
                 ("Test results", "Judge relevance, traceability and what they mean for the design."),
             ]},
            {"type": "process", "title": "Evaluating and improving",
             "steps": [
                 ("Evaluate", "Against purpose, conditions, cost and value."),
                 ("Compare", "Options using fitness for purpose and metrics."),
                 ("Review", "Individual, team and organisational performance, KPIs."),
                 ("Respond", "Confirm new requirements and log changes."),
             ]},
        ],
        "quiz": [
            ("Name three factors when selecting a modelling tool.", "Any three of: cost, availability, compatibility, training, time."),
            ("What is value engineering?", "Improving value by reducing cost without losing function."),
            ("Why log design changes?", "To keep a traceable record of decisions and their impact."),
        ],
        "activity": {
            "title": "Compare three designs",
            "time": "30 minutes",
            "format": "Small groups",
            "steps": [
                "Your teacher gives you three design options for a hinge.",
                "Build a weighted comparison matrix.",
                "Identify the likely failure mode of each.",
                "Recommend one and suggest an improvement.",
            ],
            "success": [
                "Criteria weighted sensibly",
                "Failure modes realistic",
                "Recommendation justified",
            ],
        },
        "exit": [
            "What is the most useful design evaluation tool?",
            "How do test results change a design?",
            "How should you respond to negative feedback?",
        ],
    },
    {
        "area": "spec",
        "file": "specialism/11-designing-modelling-and-prototyping.pptx",
        "title": "Designing, Modelling and Prototyping",
        "unit": "Mechanical: Performance Outcome 4",
        "spec": "Outcome 4 (4.1 to 4.8)",
        "pages": [PRAC],
        "objectives": [
            "Develop concepts that address requirements and justify materials.",
            "Model linear, rotating and lifting systems.",
            "Produce CAD representations and detailed drawings to standards.",
            "Build models and prototypes safely using hand and powered tools.",
        ],
        "starter": "What is the difference between a model and a prototype?",
        "slides": [
            {"type": "cards", "title": "From ideas to designs",
             "cards": [
                 ("Concepts", "Sketch ideas into detailed, annotated concepts."),
                 ("Mechanical modelling", "Linear systems, rotating systems (gears, flywheels), lifting machines."),
                 ("CAD", "2D and 3D drawings, simulations, accurate 3D assemblies."),
                 ("Detailed drawings", "Accuracy, tolerances, units, scale and symbols to BS and ISO."),
             ]},
            {"type": "table", "title": "Models and prototypes",
             "header": ["Type", "Use"],
             "widths": [3, 5.6],
             "rows": [
                 ["Block model", "Check size, form and proportion"],
                 ["Rapid prototype / 3D print", "Check fit and function quickly"],
                 ["One-off prototype", "Test the real material and manufacture"],
             ],
             "caption": "Requirements: dimensions (fit, form), aesthetics, mechanical properties and cost."},
            {"type": "bullets", "title": "Tools, assembly and realisation",
             "bullets": [
                 "Use hand and power tools safely, with checks before, during and after use.",
                 "Use at least one welding type and one 3D printing type when prototyping.",
                 "Assemble and disassemble safely: sequence, alignment, fixing, tensioning, sealing, testing.",
                 "Check the design can be manufactured, operated and maintained.",
             ],
             "callout": "A design isn't finished until someone could actually make it and look after it."},
        ],
        "quiz": [
            ("What is a block model for?", "Checking size, form and proportion."),
            ("Why release tension or pressure before disassembly?", "Stored energy could cause injury."),
            ("Name two pre-use checks on a power tool.", "E.g. guards fitted, cable undamaged, correct bit or blade, calibration."),
        ],
        "activity": {
            "title": "Prototype sprint",
            "time": "60 minutes",
            "format": "Pairs, practical, can run over two lessons",
            "steps": [
                "Design a phone stand with an adjustable angle.",
                "Produce a 3D CAD model and a detailed drawing.",
                "3D print or build a block model.",
                "Test it and annotate improvements.",
            ],
            "success": [
                "Drawing follows standards",
                "Model built safely",
                "Improvements based on testing",
            ],
        },
        "exit": [
            "When would you choose a one-off prototype over a 3D print?",
            "Why annotate concept sketches?",
            "What makes a design realisable?",
        ],
    },
    {
        "area": "spec",
        "file": "specialism/12-collaboration-risk-and-quality-assurance.pptx",
        "title": "Collaboration, Risk and Quality Assurance",
        "unit": "Mechanical: Performance Outcome 5",
        "spec": "Outcome 5 (5.1 to 5.5)",
        "pages": [PRAC],
        "objectives": [
            "Follow professional standards, policies and safe working practice.",
            "Work effectively with others to complete tasks.",
            "Complete risk management analyses for engineering activities.",
            "Test models and quality assure design information.",
        ],
        "starter": "You spot an error in a colleague's drawing the day before it goes to the client. What do you do?",
        "slides": [
            {"type": "cards", "title": "Standards and teamwork",
             "cards": [
                 ("Professional standards", "Engineering Council, IMechE, IET."),
                 ("Policies", "Workplace policies, SOPs, health and safety requirements."),
                 ("Teamwork", "Contribute, respond to input, manage deadlines and changing conditions."),
             ]},
            {"type": "cards", "title": "Risk management",
             "cards": [
                 ("Contexts", "Machining, mechanical handling, high-power applications."),
                 ("Mitigation", "Identify and apply controls."),
                 ("Unfamiliar situations", "Stop, assess and ask."),
                 ("Commercial risk", "Ranking models to prioritise business risks."),
             ]},
            {"type": "process", "title": "Testing and quality assuring",
             "steps": [
                 ("Model", "Virtual or physical models and prototypes."),
                 ("Test", "Concept, functional, measurement, visual inspection."),
                 ("Report", "Record and respond to results."),
                 ("Check", "Drawings for quality, compliance and completeness."),
             ]},
        ],
        "quiz": [
            ("Name two professional engineering bodies.", "Any two of: Engineering Council, IMechE, IET."),
            ("What should you do in an unfamiliar risky situation?", "Stop, assess the risk and seek advice."),
            ("What does quality assuring a drawing involve?", "Checking accuracy, technical compliance and completeness."),
        ],
        "activity": {
            "title": "Peer check",
            "time": "25 minutes",
            "format": "Pairs",
            "steps": [
                "Swap a drawing you produced with a partner.",
                "Check it against a quality checklist.",
                "Give feedback professionally.",
                "Correct your own drawing from the feedback.",
            ],
            "success": [
                "Checklist fully used",
                "Feedback is constructive",
                "Corrections made",
            ],
        },
        "exit": [
            "Why do professional standards matter?",
            "What makes a good team member?",
            "Name a high-power application risk.",
        ],
    },
    {
        "area": "spec",
        "file": "specialism/13-technical-documentation-and-communication.pptx",
        "title": "Technical Documentation and Communication",
        "unit": "Mechanical: Performance Outcome 6",
        "spec": "Outcome 6 (6.1, 6.2)",
        "pages": [PRAC],
        "objectives": [
            "Produce, manage and version-control technical documentation.",
            "Annotate drawings with tolerances, fits and surface finishes.",
            "Communicate design information to technical and non-technical audiences.",
        ],
        "starter": "Two engineers are working from different versions of the same drawing. What could go wrong?",
        "slides": [
            {"type": "cards", "title": "Managing documentation",
             "cards": [
                 ("Documents", "Design specifications and engineering drawings."),
                 ("Digital tools", "CAD, document management systems, SharePoint, spreadsheets."),
                 ("Version control", "Revision letters, change notes, one current version."),
                 ("Annotation", "Geometrical tolerances, limits and fits, surface finishes."),
             ]},
            {"type": "compare", "title": "Communicating design information",
             "left": ("Formats", [
                 "Sketches and schemes",
                 "Detailed drawings and diagrams",
                 "Models",
                 "Reports",
             ]),
             "right": ("Choosing a format", [
                 "Cost and time",
                 "Availability",
                 "The end user",
                 "The scale of the project",
             ])},
        ],
        "quiz": [
            ("Why use revision letters on drawings?", "To show which version is current and track changes."),
            ("Name two digital tools for managing documentation.", "Any two of: CAD, document management systems, SharePoint, spreadsheets."),
            ("Which format suits a non-technical client?", "E.g. a rendered model, sketch or plain-language report."),
        ],
        "activity": {
            "title": "Document pack",
            "time": "30 minutes",
            "format": "Pairs",
            "steps": [
                "Take a design you have worked on.",
                "Produce a revision-controlled drawing with full annotations.",
                "Write a one-page summary for the client.",
                "Log one design change with a change note.",
            ],
            "success": [
                "Annotations correct",
                "Revision control used",
                "Summary suits a non-technical reader",
            ],
        },
        "exit": [
            "What is a surface finish symbol for?",
            "Why is SharePoint useful for teams?",
            "How do you choose a communication format?",
        ],
    },
]
